### ISSUE TITLE
arrayOfModelsFromDictionaries doesn't behave as documented

### ISSUE THREAD

**Issue by j-h-a** [icanzilb/JSONModel#103]
I noticed this while working on pull request #102 - the method is used internally and I enhanced it to support error-checking. However since it's a documented public method and used in the demo code, I didn't want to break it so I preserved existing behaviour for that method.

However,  I read the docs for it as I did this and it states that exceptions are thrown on errors. This doesn't happen, it just returns nil or errors without explanation.

Recommended fix:
Deprecate the non-error checking version and make the error-checking version public instead. Also fix docs to say that is sets the passed in `NSError**` instead of throwing exceptions.

**Comment by billinghamj** [comment]
We should mark `+arrayOfModelsFromDictionaries:` as deprecated (but not unavailable) such that it will show a warning.
