### ISSUE TITLE
EXCEPTION: [JSONValueTransformer __JSONObjectFromNSException:] not found

### ISSUE THREAD

**Issue by gtasko** [icanzilb/JSONModel#204]
Hi,

I know this might be inappropriate to post as an issue but I need a hint in how I can resolve this.

First let me try to explain why I prefixed the JSONModel files. In no way trying to copyright or anything, I wish I could find a way to embed JSONModel source code into my static library without the risk of developers to get duplicate symbols if they will use JSONModel in their application.

So the only way to avoid it is to change naming (prefix) your classes and distribute my library.

But, after renaming the source code I got this exception when trying to get the JSON fixture from a model.

SLKJSONModel.m:1049] EXCEPTION: [JSONValueTransformer __JSONObjectFromNSException:] not found

Everything works GREAT in your code before. I just renamed all the classes, compile seemed to be happy with the results, but now I have this issue!

Any idea where to look?

Thank you in advance.

**Comment by billinghamj** [comment]
There are several parts of JSONModel which use strings or selectors to call methods to prevent compiler errors/warnings. Look for things like `NSClassFromString`, `@selector`, `SEL`, etc.
