### ISSUE TITLE
ConditionalJSONModel

### ISSUE THREAD

**Issue by dbachrach** [icanzilb/JSONModel#229]
We have a JSON API that returns an array of objects. The objects do not have to be the same type. The type of the object is encoded in one of the object's properties. Example:

```json
[
    { 
        "type": "user",
        "name": "Dustin"
    },
    {
        "type": "group",
        "title": "My Group"
    }
]
```

I want to transform this JSON into an array of 2 objects-- MYUser and MYGroup. To accomplish this right now with JSONModel, I have created a ConditionalJSONModel class at [this gist](https://gist.github.com/dbachrach/4b73e88625edadcbde74).

I can then create a MYConditionalModel:

```objc
@interface MYConditionalModel : ConditionalJsonModel

@end

@implementation MYConditionalModel

- (NSString*)classNameProperty
{
    return @"type";
}

- (NSDictionary*)classMapping
{
    return @{ @"user": MYUser.class, @"group": MYGroup.class };
}

- (BOOL)requiresExactMatch
{
    return YES;
}

@end
```

This has worked well for us, and I wanted to see if you guys want to incorporate something like ConditionalJSONModel into core.

**Comment by caoer** [comment]
@icanzilb @nitya1806 @dbachrach 

I think it will be very useful to add this feature. Perhaps it can take how Mantle handle it as a reference. Adding an ability to let user choose class should be used when deserializing an object from JSON

https://github.com/Mantle/Mantle#classforparsingjsondictionary

**Comment by billinghamj** [comment]
I think it'd be worth discussing this more. Personally, I really do think this should be limited to subclasses though to prevent general confusion (especially when calling an `init` method on a class, it really must return a instance which is that kind of class).

**Comment by dbachrach** [comment]
To chime back in here. We landed on a class-cluster model and it's been working great for us. Doesn't require any change to JSONModel either.

**Comment by billinghamj** [comment]
@dbachrach presumably similar to the code I have above? Might be worth documenting a simple example of it in the readme.

**Comment by dbachrach** [comment]
Yep very similar @billinghamj 

When I have some time, I can put together a short addition to the readme for this use case.
