### ISSUE TITLE
Persisting Models

### ISSUE THREAD

**Issue by Urkman** [icanzilb/JSONModel#232]
Are there any plans to add a persisting layer?

**Comment by Shamsiddin** [comment]
how to map into NSManagedObject class objects? Is there any support for NSManagedObject model classes?

**Comment by billinghamj** [comment]
JSONModel does not support CoreData.

**Comment by Shamsiddin** [comment]
It'd be great addition.

**Comment by billinghamj** [comment]
It was attempted a while ago, but didn't end well.

**Comment by billinghamj** [comment]
https://github.com/icanzilb/JSONModel/issues/306#issuecomment-165432075
