### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by costabas** [icanzilb/JSONModel#250]
The compilation fails in JSONHTTPClient.m at line 387 with Use of undeclared identifier 'UIApplication'.

#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
[[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:isVisible]; <-- It fails here.
#endif

To fix it I added this (in JSONHTTPClient.m):

#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
#import &lt;UIKit/UIKit.h&gt;
#endif

just below #import "JSONHTTPClient.h"

**Comment by alexleone** [comment]
I got this same error, when I am not using the POD 1.0.2. If I drag in the JSONModel Folder into my project it will throw this error described. I always end up just commenting out
#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
//    [[UIApplication sharedApplication] setNetworkActivityIndicatorVisible:isVisible];
#endif

**Comment by xmarcusv** [comment]
I got this same error. Thaks @costabas

**Comment by GuillaumeJasmin** [comment]
Thanks @costabas for the fix !

**Comment by JonathanLink** [comment]
I have the error, too. (obj-c - iOS 7.0 project) 
I had to comment the line too.

**Comment by billinghamj** [comment]
Likely related to the fact that new projects don't include a precompile header. Previously, precompile headers defaulted to including:

```objc
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
```

**Comment by billinghamj** [comment]
That being said, the offending line of code no longer seems to exist.
