### ISSUE TITLE
JSON Object within Object (No Arrays!)

### ISSUE THREAD

**Issue by flagsoft** [icanzilb/JSONModel#251]
I want to have something like this (no arrays!):

{
  "devices": {
    "DevA": {
      "name": "DevA",
      "capacity": "1.0"
    },
    "DevB": {
      "name": "DevB",
      "capacity": "2.0"
    }
  }
}

How can I read that?
(Hint: DevA and DevB .... etc... DevXYZ is not defined. It is also not defined how many entries there are.)

**Comment by Anupdas** [comment]
If you have luxury to change the structure it would be most appropriate 

```
{
  "devices": [
    {
      "name": "DevA",
      "capacity": "1.0"
    },
    {
      "name": "DevB",
      "capacity": "2.0"
    }
  ]
}
```
So if a new DevC or DevD comes it would be easier. If they all the items with prefix of ```Dev``` has same structure you can reformat the structure within a custom setter

**Comment by billinghamj** [comment]
This can be done pretty easily. The following models would work:

```objc
@protocol MyDevice;

@interface MyDevice : JSONModel

@property (strong, nonatomic) NSString *name;
@property (strong, nonatomic) NSString *capacity;

@end

@interface MyModel

@property (strong, nonatomic) NSDictionary <MyDevice> *devices;

@end
```
