### ISSUE TITLE
Accessing properties, not working

### ISSUE THREAD

**Issue by flagsoft** [icanzilb/JSONModel#252]
Why does this works:
    ProductModel *myProduct = d.products[1];    
    NSLog(@"d:%@", myProduct.name);

But this not?
    //NSLog(@"d:%@", d.products[1].name );

Model:

(Example: Lazy convert collection items from dictionaries to models on https://github.com/icanzilb/JSONModel)

{
  "order_id": 104,
  "total_price": 103.45,
  "products" : [
    {
      "id": "123",
      "name": "Product #1",
      "price": 12.95
    },
    {
      "id": "137",
      "name": "Product #2",
      "price": 82.95
    }
  ]
}

@protocol ProductModel
@end

@interface ProductModel : JSONModel
@property (assign, nonatomic) int id;
@property (strong, nonatomic) NSString* name;
@property (assign, nonatomic) float price;
@end

@implementation ProductModel
@end

@interface OrderModel : JSONModel
@property (assign, nonatomic) int order_id;
@property (assign, nonatomic) float total_price;
@property (strong, nonatomic) NSArray<ProductModel, ConvertOnDemand>* products;
@end

@implementation OrderModel
@end

**Comment by billinghamj** [comment]
It's actually because the type of `array[1]` is actually `id` - not your model class.

With very recent version of Objective-C, you can define your properties like this:

```objc
@property (strong, nonatomic) NSArray <ProductModel *> <ProductModel> *products;
```

This is a compile-time-only generics system. The first angle brackets are the array's type arguments. The second angle brackets define the protocols - which JSONModel uses.

**Comment by zhiyuzhao** [comment]
the following is on your README.md
> @property (strong, nonatomic) NSArray<ProductModel>* products;

I think this need update it with 
`@property (strong, nonatomic) NSArray <ProductModel *> <ProductModel> *products;`
Otherwise some people like me will think the angle brackets is compile-time-only generics system.

**Comment by billinghamj** [comment]
I'll add a note explaining that this is a protocol and unrelated to the recently-added generics support. Having both would look quite confusing though I think.
