### ISSUE TITLE
Optional property defined in Swift cannot be determined correctly

### ISSUE THREAD

**Issue by KrissLiu** [icanzilb/JSONModel#258]
I am using JSONModel library in a project which uses Swift as main programming language. I defined a model class with an optional property and tried to deserialize from JSON string returned from server. The operation failed because JSONModel library cannot recognise optional property defined by swift.

Here is an example:
```
class AuthModel : JSONMOdel {
   var token : NSString?
}
```

And the error message:
```
[JSONModel.m:252] Incoming data was invalid 
fatal error: unexpectedly found nil while unwrapping an Optional value
```

When I looked into the source code. I found the property attribute might be different between Swift and Objective-C:
```
T@"NSString",N,&,Vtoken
```

There's no "\<Optional\>" protocol in property attributes.

Hope this issue could be fixed soon.

Thanks,
Kriss

**Comment by billinghamj** [comment]
Best option while still using JSONModel is to define the models in Obj-C.

JSONModel fundamentally works on the principles of defining its behavior via protocols. If you stop doing that, it's effectively a different library anyway. Maybe a better option for you would be to use a native Swift library?

**Comment by icanzilb** [comment]
Yes, trust me - if there was a sane way to make JSONModel work with the new Swift goodness I would've done in last year already.

**Comment by Tyson775** [comment]
Please use following code in the sub class of your json model. if you want to give all the properties as optional then use like this,

override class func propertyIsOptional(propertyName: String!) -> Bool {
        return true
    }

else if for a specific property means,
override class func propertyIsOptional(propertyName: String!) -> Bool {
        if propertyName == "your_property_name"
        {
            return true
        }
        return false
    }
