### ISSUE TITLE
Is there a way to stringify to json objects that do not inherit from JSONModel?

### ISSUE THREAD

**Issue by pikaboo** [icanzilb/JSONModel#263]
I need to archive an object i received from a closed SDK
I cannot make it inherit from JSONModel

in java, for example, i can stringify any object using the gson library, and simply providing the class of the object
is there a way to do that in jsonmodel ?

example in 
        java MyModelClass object = new Gson().fromJson(jsonString,MyModelClass.class);

**Comment by billinghamj** [comment]
I'm afraid not. You could copy the data in it to an equivalent class inheriting from JSONModel though.
