### ISSUE TITLE
Generic Model Class

### ISSUE THREAD

**Issue by Urkman** [icanzilb/JSONModel#264]
Hello,

I'm currently trying to include JSONModel to a project I'm currently working on...
In this project I need to get data from a web service, that always returns me same data structure, but with different entries...
So I build a base JSONModel class that should work with all the responses. I looks like this:

@interface WebserviceResponse : JSONModel

@property (assign, nonatomic) BOOL success;
@property (assign, nonatomic) int code;
@property (strong, nonatomic) NSString *message;
@property (strong, nonatomic) NSString *timestamp;
@property (strong, nonatomic) NSArray<Optional> *list;

@end

The data I get from the web service is always given in "list" and is always a dictionary (but it differs with the different API methods I call). Except on an error it is "null"...

How can I define this list property to simply parse the given dictionaries?
With the given structure my object is always null :(

Thanks for your help,
Urkman

**Comment by billinghamj** [comment]
Even if JSONModel didn't know what class the objects in `list` were, it would still correctly deserialize them into at least `NSDictionary` instances.

Sounds like your API might be returning an error?

You can create subclasses of `WebserviceResponse` with the `list` property, specifying the class which should be used for deserialization via a protocol.
