### ISSUE TITLE
How can i get the raw-style data after the function "getJSONFromURLWithString()"

### ISSUE THREAD

**Issue by izongzi** [icanzilb/JSONModel#268]
JsonModel will sort data accroiding to id(number) automatically , but i dont need this automatic sorting , so what can i do?

**Comment by billinghamj** [comment]
There's nothing in JSONModel which will change the order of elements in an array.

If you want more control over how your data is being retrieved, you'd be best using a more comprehensive networking library in addition to JSONModel - e.g. NSURLSession, AFNetworking, etc.
