### ISSUE TITLE
modelWithIndexValue:  can not work well when JSONModelArray invoke it directly

### ISSUE THREAD

**Issue by lianchengjiang** [icanzilb/JSONModel#270]
there is a ConvertOnDemand property in a model。so this property is a JSONModelArray，when it  invoke modelWithIndexValue: ,the _storage[0] is a dictionary, so it can not respond indexPropertyName。

    if (![_storage[0] indexPropertyName]) return nil;

[__NSDictionaryI indexPropertyName]: unrecognized selector sent to instance 0x7f8569d63ea0

**Comment by billinghamj** [comment]
I'm pretty sure this won't happen any more due to changes which have happened since. Please feel free to make a new issue if the problem still persists in the latest version.
