### ISSUE TITLE
How to access Property of an array individual Object

### ISSUE THREAD

**Issue by itsaboutcode** [icanzilb/JSONModel#273]
I have following schema

       #import <Foundation/Foundation.h>
       #import "JSONModel.h"
       @class PResponse;
       @class PDate;
       @class PNurse;
       @class PPatientData;
       @class PProvider;

       @protocol PData

       @end

       @interface RNurse : JSONModel
       @property (nonatomic, strong) NSString *fname;
       @property (nonatomic, strong) NSString *lname;
       @end

       @interface RPatientData : JSONModel
       //@property (nonatomic, strong) NSString *fname;
       //@property (nonatomic, strong) NSString *lname;
       @end

       @interface RProvider : JSONModel
       @property (nonatomic, strong) NSString *fname;
       @property (nonatomic, strong) NSString *lname;
       @end

       @interface PData : JSONModel
       @property (nonatomic, strong) PNurse *Nurse;
       @property (nonatomic, strong) PPatientData *PatientData;
       @property (nonatomic, strong) PProvider *Provider;
       @end

       @interface PResponse : JSONModel
       @property (nonatomic, strong) NSString *code;
       @property (nonatomic, strong) NSString *msg;
       @property (nonatomic, strong) NSArray <PData> *data;
       @end

       @interface PatientResponse : JSONModel

       @property (nonatomic, strong) PResponse *response;

       @end

But when I try to do this.

       PatientResponse *patientResponse = [[PatientResponse alloc] initWithDictionary:info error:&error];
        PProvider *provider = [[patientResponse.response.data objectAtIndex:0] Provider];
        NSLog(@"%@",provider.fname); // I get error on this line
        // Property 'fname' cannot be found in forward class object 'PProvider'

**Comment by billinghamj** [comment]
This is an issue with your use of Obj-C, not JSONModel.

You need to import the header where `PProvider` is defined, e.g.:

```objc
#import "PProvider.h"
```
