### ISSUE TITLE
JSONModel does not alllow you to override the default JSONValueTransformer transforms

### ISSUE THREAD

**Issue by MikeLeber117** [icanzilb/JSONModel#274]
I have a problem where a web API response contains a URL string to a web resource with spaces in the name of the file. I need to percent encode this before setting it to the NSURL instance (otherwise the NSURL will not be created and you get nil for that property).

The difficulty arrises in the interaction between the default JSONValueTransformer and JSONModel. The default transformer has an implementation for NSString -> NSURL, but it does not take into account needing to percent encode. But because JSONModel does not allow you to inject your own JSONValueTransformer into the system (it instead tells you to use a category, but you cannot override methods in a category). 

Is it possible to get a change where a client can define a custom sub class of JSONValueTransformer that JSONModel uses (or otherwise inject there own)?

I could just store an NSString property with a transient NSURL getter that than does the encoding, but it would be nice to handle everything in JSONModel.

**Comment by JoachimK** [comment]
I had a similar problem and found a way to solve it:

JSONModel will first look for custom accessors before using the value transformer. I'm not sure whether this is `public` API as it's not documented anywhere I could find but works well.

Simply create a custom setter and getter of the form:

    set[PropertyName]With[ClassName]:([[ClassName] *)arg;
    ([ClassName] *)JSONObjectFor[PropertyName]

For example a had a `birthday` property which is of type `NSDate` and deserialized from a JSON string so I implemented the following methods:

    - (void)setBirthdayWithNSString:(NSString *)birthdayString;
    - (NSString *)JSONObjectForBirthday;

Works fine for me.

@icanzilb Could you tell us whether we can consider this functionality public API? It certainly feels like it should be used exactly like that but I couldn't find any documentation about it. I only found it by reading the code to find a way to specify my custom value transformation. ;-)

**Comment by scotbond** [comment]
Had similar problem, opened PR for it: https://github.com/icanzilb/JSONModel/pull/297.

**Comment by scott-ce** [comment]
+1 for clarifying whether `setPROPERTYWithTYPE:` and `JSONObjectForPROPERTY` are considered public. We were actually planning to migrate away from JSONModel because it seemed too inflexible for special cases like this… until I noticed these methods, which have been very useful.

**Comment by icanzilb** [comment]
this is incredibly public - you can totally use it, and I've answered a number of issues on GitHub recommending using it :+1:

**Comment by scott-ce** [comment]
Sweet. Might be helpful to add it to the README. Noticed it still says 1.0.2 as well. I'm happy to submit a PR for the README later today if it helps?

Thanks for the response and very cool library!

**Comment by icanzilb** [comment]
sure - add an example how to do that and send over the pr
