### ISSUE TITLE
Where Exactly I should set GlobalKeyMapper? 

### ISSUE THREAD

**Issue by itsaboutcode** [icanzilb/JSONModel#275]
I am subclassing my BaseModel from JSONModel so that I can put things like 
     
     [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase] 

or ignore all the values. But I am not sure where to put following command?

    [JSONModel setGlobalKeyMapper:[
                                   [JSONKeyMapper alloc] initWithDictionary:@{
                                                                              @"item_id":@"ID",
                                                                              @"item.name": @"itemName"
                                                                              }]
     ];

**Comment by icanzilb** [comment]
in your own code before you create any models
