### ISSUE TITLE
In JSON file, a key has null value, how to fix this?

### ISSUE THREAD

**Issue by zhw511006** [icanzilb/JSONModel#277]
If we make all model properties optional, what will happen?

Because JSON file miss some keys sometimes, I can't decide which one can be missed and I hope the app can get data also. 

Thx!

**Comment by zhw511006** [comment]
I get it, we can use <Optional>.

**Comment by xingheng** [comment]
[RTFM](https://github.com/icanzilb/JSONModel/blob/master/README.md) first please! You could overwrite the class method like this:

+(BOOL)propertyIsOptional:(NSString*)propertyName
{
  return YES;
}

**Comment by zhw511006** [comment]
I already have saw this, But It says that "avoid if possible", so I want to know what will happen if I do like this, thx!

**Comment by xingheng** [comment]
Try it and you'll know "what will happen".

It will assume all the properties of your entity class are implemented Optional protocol.
