### ISSUE TITLE
how should i do ?

### ISSUE THREAD

**Issue by xlking** [icanzilb/JSONModel#279]
comments": [
      {
        "commentId": 12345,
        "userPhoto": "http://attach.etiantian.com/ett20/study/common/upload/7878_11550794_50_50.jpg",
        "userName": "小明",
        "userCity": "湖南长沙",
        "userType": 0,
        "jid": 7878,
        "commentTime": "1分钟前",
        "commentContent": "这是评论,评论内容",
        "commentIndex": 1,
        "commentReplyCnt": 1,
        "commentPrise": 10,
        "isBlocked":0,
        "target": {}
      },
      {
        "commentId": 12346,
        "userPhoto": "http://attach.etiantian.com/ett20/study/common/upload/7878_11550794_50_50.jpg",
        "userName": "小红",
        "userCity": "北京",
        "userType": 0,
        "jid": 7879,
        "commentTime": "1分钟前",
        "commentContent": "我回复了一个评论",
        "commentIndex": 2,
        "commentReplyCnt": 0,
        "commentPrise": 0,
        "isBlocked":1,
        "target": {
          "commentId": 12345,
          "userName": "小明",
          "userCity": "湖南长沙",
          "commentIndex": 1,
          "isBlocked":0,
          "jid": 7878,
          "commentContent": "这是评论,评论内容"
        }
      }
    ]

this is a json string , "comments" is an array, "target" is a dictionary, i use NSDictionary<TargetModel, Ignore> *target ，the second target is null ? how should i do ? optional or other? thanks~~

**Comment by icanzilb** [comment]
is this an issue you are reporting with the code?

**Comment by xlking** [comment]
No, I just want to know, what should I do, “target” can have the data

**Comment by icanzilb** [comment]
Then why did you report an issue at the code repository? If you have a key that can be null it needs to be defined with the Optional protocol ... at least read the documention this is covered many times

**Comment by xlking** [comment]
optional ?  “target”  key  must  apear, that is a dictionary, if there is no key ,jsonmodel think that is not a dictionary,An exception is thrown。if i use "ignore" markup the "target",the seconde "targer" dictionary has nothing value.
