### ISSUE TITLE
need for use another keymapper occasionally

### ISSUE THREAD

**Issue by zhangciwu** [icanzilb/JSONModel#280]
now keyMapper is a class method
so it's settle down before run.

but, sometimes I want to use another keymapper for one or two time
for example, I want to get under_score case to camelCase json string in some cases, not all the time

to meet this need, there is some solution:
1. add keyMapper method for object ( - )
2. add <code>toJSONStringWithKeyMapper:</code> method or something like this

**Comment by billinghamj** [comment]
You could achieve this by subclassing your model and giving overriding the key mapper in the subclass.
