### ISSUE TITLE
array to json

### ISSUE THREAD

**Issue by f33chobits** [icanzilb/JSONModel#282]
Hey @icanzilb 
   I've been using this lib for a long time, and waited to an updating which a NSArray category could 'toJSONString', but it never come. So maybe this lib cannot add that feature? Maybe on purpose?

**Comment by Anupdas** [comment]
An array of model can be exported to array of dictionaries. You can then easily serialize this array to JSON. 

```objc
NSArray *arrayOfModels = //array of models
NSArray *arrayOfDictionaries = [CustomModel arrayOfDictionariesFromModels:arrayOfModels];
NSString *json = //Use NSJSONSerialization to create Json
```

**Comment by f33chobits** [comment]
Thanks ~ :+1:
