### ISSUE TITLE
Working with NSArrays inside JSONModel

### ISSUE THREAD

**Issue by Miguelme** [icanzilb/JSONModel#284]
I have a JSONModel that has a NSArray inside but the NSArray is not parsing properly, the elements inside them are being treated as NSDictionary. How can i avoid that and parse the elements of the NSArray to the proper JSONModel ?

I have something like that 

Model1.h

@interface Model1 : JSONModel
@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSArray *list;
@end 

the list is not parsing, is staying as a NSDictionary;

Note: I am using AFNetworking so the parsing is something like this 

modelInstance = [[Model1 alloc] initWithDictionary:responseObject error:nil];

Any help would be really appreciated.

Kind Regards,

Miguel

**Comment by JoachimK** [comment]
Did you see the part about how to specify models for your collection: https://github.com/icanzilb/JSONModel#model-collections

Basically if the class of the objects in your array is `SpecialModal` you need to do two things: 
1. Declare a __protocol__ `SpecialModel` somewhere in addition to your SpecialModel-class. I recommend to declare it either in your `Model1.h` file or in the `SpecialModel.h` file.
2. Declare that your array should only contain objects of this type like this:

    @property (nonatomic, retain) NSArray<SpecialModel> *list;

**Comment by kudo108** [comment]
if I have the json like this: 
{
"tag": ["tag1", "tag2"]
}
How can i declare it ?

**Comment by JoachimK** [comment]
Did you try to declare a protocol named `NSString`?

**Comment by huadee** [comment]
ask also

**Comment by pjebs** [comment]
Any solution to this?
Having this same issue.

**Comment by billinghamj** [comment]
@kudo108 You don't need to specify a protocol for NSString - it will implicitly use that type.

@Miguelme You need to use the protocol as stated here - https://github.com/icanzilb/JSONModel/issues/284#issuecomment-75528143

**Comment by LilJeff2626** [comment]
Still really struggling with this.  I am trying to define a protocol with NSString.
Languages.h
----------------------
#import "JSONModel.h"
@protocol Languages <NSString>
@end
@interface Languages : JSONModel
@end
Languages.m
-------------------
@implementation Languages
@end

Description.h
------------------
#import "JSONModel.h"
#import "Languages.h"

@interface Description : JSONModel
@property (strong, nonatomic) NSArray<Languages*>* languages;
@end

Nothing seems to be working....

**Comment by billinghamj** [comment]
```objc
@property (strong, nonatomic) NSArray* <Language> languages;
```

**Comment by LilJeff2626** [comment]
That didn't seem to work. 

I tried to give a better example on Assign JSONArray of Strings using JSONModel #483

**Comment by JoachimK** [comment]
Does this maybe do what you want?
```objc
@property (strong, nonatomic) NSArray* <NSString> languages;
```

Otherwise your `Language` class is missing a property that JSONModel is supposed to assign.

Could you maybe give an example of what your JSON looks like?
