### ISSUE TITLE
Lead to NSAssert compile failed.

### ISSUE THREAD

**Issue by MakeZL** [icanzilb/JSONModel#287]
File   : JSONHTTPClient.h  
line   : 130
code : NSAssert([value isKindOfClass:[NSString class]], @"request parameters can be only of NSString or NSNumber classes. '%@' is of class %@.", value, [value class]);

I hope give you some help.

**Comment by billinghamj** [comment]
This is happening because you're setting a url parameter to the wrong type. Only NSNumbers and NSStrings are allowed.
