### ISSUE TITLE
Can I create Object with readonly property?

### ISSUE THREAD

**Issue by ivampir** [icanzilb/JSONModel#289]
I'd like to create Object with readonly property. How I can do this?

**Comment by icanzilb** [comment]
Use the Objective-C syntax to define a readonly property

**Comment by ivampir** [comment]
It doesn't work :(

//OneOption.h
#import <Foundation/Foundation.h>
#import "JSONModel.h"

@interface OneOption : JSONModel

@property (nonatomic, strong, readonly) NSString* title;
@property (nonatomic, assign, readonly) BOOL visible;
@property (nonatomic, assign, readonly) BOOL attached;
@property (nonatomic, assign, readonly) BOOL editable;

@end

NSError *error = nil;
OneOption *oneOption = [[OneOption alloc] initWithDictionary:optionDict error:&error];

// return object with empty properties

**Comment by ivampir** [comment]
If remove "readonly" parameter, all will be ok. But property will be readwrite :(

**Comment by icanzilb** [comment]
JSONModel also uses property access to set the values of your model so I don't think there is any straight forward method to implement what you want

**Comment by ivampir** [comment]
Could you add this future in next time? I think It will be useful for create non mutable objects. KeyValueObjectMapping liberty can do it, but I like your liberty more

**Comment by icanzilb** [comment]
as said a property can't be read only because then JSONModel can't assign values to it

**Comment by ivampir** [comment]
I think it's possible to do :) But I don't now how

**Comment by sagaraya** [comment]
I'd also like to create Object with readonly property.

I think readonly means cannot set property from outside of class.
But, initWithDictionay set property inside of class because OneOption inherit JSONModel.

I commented out below lines, and was able to create Object with readonly property.

JSONModel.m
```objective-c
585            //ignore read-only properties
586            //if ([attributeItems containsObject:@"R"]) {
587            //    continue; //to next property
588            //}
```

Could you add this future in next time?

**Comment by AlJaMa** [comment]
@sagaraya Your patch works.  @icanzilb Is there any point at which "__inspectProperties" modifies something that does not inherit from JSONModel? (IE: the code commented out here could be removed for good)

**Comment by tecknut** [comment]
@ivampir I wanted to do this too. I found that if I mark the public properties as readonly, then redefine the properties in an extension in your m file 
```
// OneOption.h
@interface OneOption : JSONModel

@property (nonatomic, strong, readonly) NSString* title;
@property (nonatomic, assign, readonly) BOOL visible;
@property (nonatomic, assign, readonly) BOOL attached;
@property (nonatomic, assign, readonly) BOOL editable;

@end

// OneOption.m
@interface OneOption ()

@property (nonatomic, strong) NSString* title;
@property (nonatomic, assign) BOOL visible;
@property (nonatomic, assign) BOOL attached;
@property (nonatomic, assign) BOOL editable;

@end

@implementation OneOption

// implementation code

@end
```

This is kind of inconvenient, but it works. Hope this helps.
