### ISSUE TITLE
how can i set BOOL Optional?

### ISSUE THREAD

**Issue by hengchengfei** [icanzilb/JSONModel#290]
i want to set  isSubscribe Optional,but it is BOOL type,but it is error.
@property(nonatomic)BOOL<Optional> isSubscribe;

**Comment by danipralea** [comment]
```
+ (BOOL)propertyIsOptional:(NSString *)propertyName {
    if ([propertyName isEqualToString:@"isSubscribe"]) {
        return YES;
    }
    return NO;
}```

**Comment by hengchengfei** [comment]
thank you very much

**Comment by sudhiryadav** [comment]
I tried this but not working:

`+(BOOL)propertyIsOptional:(NSString*)propertyName
{
    return YES;
    if ([propertyName isEqualToString: @"isInEurope"])
    {
        return YES;
    }
    return NO;
}`

**Comment by billinghamj** [comment]
@sudhiryadav The first statement in your function is "return YES", so that is probably why it isn't working...

**Comment by sudhiryadav** [comment]
Let's keep this closed and we can follow my main question. [https://github.com/icanzilb/JSONModel/issues/444#event-549843608](url)
