### ISSUE TITLE
I set property optional ,but it doesn't work.

### ISSUE THREAD

**Issue by hengchengfei** [icanzilb/JSONModel#292]
@property(nonatomic,strong)ShareModel<Optional>* share_info;

when the app server don't transform the field, the "initWithDictionary" object = nil

but if I set the property as follows,it does works.
+(BOOL)propertyIsOptional:(NSString *)propertyName
{
   if([@"share_info" isEqualToString:propertyName]){
       return YES;
    }
}

**Comment by captain-black** [comment]
I should set a property optional like this:
@property(nonatomic,strong) ShareModel<Optional> * share_info;

**Comment by billinghamj** [comment]
You can define it as optional by using the Optional protocol:

```objc
@property (nonatomic, strong) ShareModel <Optional> *share_info;
```
