### ISSUE TITLE
init in non-UI thread?

### ISSUE THREAD

**Issue by lucastan** [icanzilb/JSONModel#293]
If `Model` does not use any custom parsing (such as NSDate), is the following safe to be invoked in a background thread?

```
[[Model alloc] initWithXXX ...]
```

**Comment by billinghamj** [comment]
Yes, JSONModel does not do any kind of UI interaction, and as such, the thread it runs on does not matter.

**Comment by lucastan** [comment]
How about any unsafe access to shared data structures?

**Comment by billinghamj** [comment]
Not to my knowledge, but this isn't an area we spend a lot of time handling.
