### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by hamzaozturk** [icanzilb/JSONModel#294]
We got a crash report related to JSONModel. You can find details and stack trace below:

Function:
__84+[JSONHTTPClient JSONFromURLWithString:method:params:orBodyData:headers:completion:]_block_invoke (in <AppName>)

0	AGXGLDriver	__84+[JSONHTTPClient JSONFromURLWithString:method:params:orBodyData:headers:completion:]_block_invoke (in <AppName>) (JSONHTTPClient.m:275)
1	AGXGLDriver	+[<ControllerName> attributionHandlerForActivityHandler:withMaxDelay:withAttributionPackage:] (in <AppName>) (<FileName>.m:66)
2	AGXGLDriver	-[<ControllerName> viewDidLoad] (in <AppName>) (<FileName>.m:50) + 155852
3	AGXGLDriver	-[<ControllerName> viewDidLoad] (in <AppName>) (<FileName>.m:59) + 182504
4	GLEngine	-[<ControllerName> startLogging] (in <AppName>) (<FileName>.m:75) + 645572
5	GLEngine	-[<ControllerName> copyWithZone:] (in <AppName>) (<FileName>.m:474) + 388708
6	QuartzCore	-[<ControllerName> getSongResults] (in <AppName>) (<FileName>.m:79) + 134688
7	QuartzCore	-[<ControllerName> viewDidLoad] (in <AppName>) (<FileName>.m:52) + 134064
8	QuartzCore	-[<ControllerName> setMainPlayerController:] (in <AppName>) (<FileName>.m:21) + 132816
9	QuartzCore	-[<ControllerName> viewDidLoad] (in <AppName>) (<FileName>.m:51) + 130392
10	QuartzCore	-[<ControllerName> alertView:clickedButtonAtIndex:] (in <AppName>) (<FileName>.m:584) + 129120
11	QuartzCore	-[<ControllerName> tableView:didSelectRowAtIndexPath:] (in <AppName>) (<FileName>.m:532) + 128376
12	QuartzCore	-[<ControllerName> tableView:viewForHeaderInSection:] (in <AppName>) (<FileName>.m:332) + 123732
13	QuartzCore	__46-[<ControllerName> loadUserPackagesAsync]_block_invoke (in <AppName>) (<FileName>.m:113) + 117652
14	libdispatch.dylib	0x000000010000136c (in <AppName>) + 4972
15	libdispatch.dylib	-[<ControllerName> appWillOpenUrlInternal:] (in <AppName>) (<FileName>.m:395) + 46272
16	libdispatch.dylib	0x0000000100004474 (in <AppName>) + 17524
17	libdispatch.dylib	-[<ControllerName> updateWithRichPushObject:] (in <AppName>) (<FileName>.m:81) + 53796
18	libdispatch.dylib	-[<ControllerName> viewDidLoad] (in <AppName>) (<FileName>.m:261) + 59228
19	libsystem	_pthread.dylib 0x00000001000012e4 (in <AppName>) + 4836
20	libsystem	_pthread.dylib 0x0000000100000fa8 (in <AppName>) + 4008

I changed some special controller's and method's name. They are not related to JSONModel.

**Comment by billinghamj** [comment]
Which exact version of JSONModel were you using?

**Comment by billinghamj** [comment]
Closed due to 2 weeks of inactivity - open a new issue if you still need help with this.
