### ISSUE TITLE
When init a JSONModelArry, but I can't get error if one of JSON object in the array missing some attribute.

### ISSUE THREAD

**Issue by captain-black** [icanzilb/JSONModel#295]
About JSONModelArray，
When init a JSONModelArry, but I can't get error if one of JSON object in the array missing some attribute.
[[JSONModelArray alloc] initWithArray:responseObject[@"My"] modelClass:[MyModel class]];

I think this will be better:
[[JSONModelArray alloc] initWithArray:responseObject[@"My"] modelClass:[MyModel class] error:&error];

**Comment by billinghamj** [comment]
You should not directly initialize `JSONModelArray`. It is only used internally for handling `ConvertOnDemand` properties.

Use one of the following instead:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
- `+arrayOfModelsFromString:error:`
