### ISSUE TITLE
Wrong `-(NSUInteger)hash` implementation

### ISSUE THREAD

**Issue by yanke-guo** [icanzilb/JSONModel#298]
The implementation of hash is below
```
- (NSUInteger)hash
{
    if (self.indexPropertyName) {
        return [self.indexPropertyName hash];
    }
    
    return [super hash];
}
```

However, It will generate always the same value.

Took me a long time to debug.

**Comment by yanke-guo** [comment]
JSQMessagesController use `[NSObject hash]` to cache cell size.

**Comment by billinghamj** [comment]
Why would it always generate the same value? The implementation looks correct to me.

Are you using the `Index` protocol?

**Comment by yanke-guo** [comment]
I believe ur hashing the name of index property, not the value of the index property.

**Comment by icanzilb** [comment]
that looks like a bug yes

**Comment by billinghamj** [comment]
Ah, I see. That should be pretty easy to fix.

Something like this perhaps:

```objc
- (NSUInteger)hash
{
    if (self.indexPropertyName) {
        id val = [self valueForKey:self.indexPropertyName];
        if (val)
            return [val hash];
    }

    return [super hash];
}
```

**Comment by icanzilb** [comment]
yes, looks good to me

**Comment by billinghamj** [comment]
Let me know if this issue persists/comes back
