### ISSUE TITLE
Optional property set  by '+ (BOOL)propertyIsOptional:(NSString *)propertyName', toDictionary error

### ISSUE THREAD

**Issue by simalone** [icanzilb/JSONModel#301]
Property is optional set by  '+ (BOOL)propertyIsOptional:(NSString *)propertyName',  the property is not NSObject class, like int type,  so can't user <Optional>.  While  the property of a model is not set, using [model toDictionary],  the return dictionary include the property with 0 value. I don't think the return dictionary should include the property key.

**Comment by sauvikatinnofied** [comment]
Are you expecting those properties from the incoming  json?

**Comment by billinghamj** [comment]
It isn't really possible to handle this any other way. In Obj-C, using scalar types, there is absolutely no difference between not setting a value and setting zero.

If you want to differentiate between no value and zero, you need to use an object type, like `NSNumber`.
