### ISSUE TITLE
NSArray and custom data transformer

### ISSUE THREAD

**Issue by skerkewitz** [icanzilb/JSONModel#302]
Hey there,

I have a class *Ident* subclassing *NSObject*. I also wrote a custom data transformer for *Ident*. So if 
i use the type *Ident* directly in a JSONModel class everything works as expected.

So this works fine:
```objective-c
@interface SomeData : JSONModel
@property (strong,  nonatomic) Ident *someIdent; // Custom transformer will make this an Ident
@property (strong, nonatomic) NSDate *date;
@property (strong, nonatomic) NSString *text;
@end
```

But if is do something like
```objective-c
@protocol Ident; // Forward declaration. 

@interface IdentList : JSONModel
@property (assign, nonatomic) NSUInteger count;
@property (assign, nonatomic) BOOL hasMore;
@property (strong, nonatomic) NSArray<Ident> *data; // array of NSNumber but should be array of Ident
@end
```

then the data array will be of type *NSNumber* or *NSString* (depending on whats in the JSON) and not of type *Ident*.  I did a brief look over the JSONModel code and to me it seems that if the protocol does not extends JSONModel no transformation is done on the array.

In both cases *Ident* looks more or less like this:
```objective-c
// --- Ident looks more or less like this
@interface Ident : NSObject
@property (strong, nonatomic) NSNumber *ident;
@end
```

**So my question is**: am I doing something wrong or is that case indeed not supported by JSONModel?

Stefan

**Comment by LucasVidal** [comment]
Same issue here. Thanks!

**Comment by billinghamj** [comment]
Looks like this is probably the same as #406.

**Comment by billinghamj** [comment]
Closing in favor of #406.
