### ISSUE TITLE
NSArray element type

### ISSUE THREAD

**Issue by mr-const** [icanzilb/JSONModel#304]
Is it possible to pass NSArray element type to JSONModel object?

something like this:
```
@interface ResponseEntityList : JSONModel<ItemType>
@property (strong, nonatomic) NSArray<ItemType>* data;
@end

ResponseEntityList<VideoItem>* list = [[ResponseEntityList alloc] initWithDictionary: dict error: &err];
```

**Comment by pbassut** [comment]
Did you take a look in the readme?
You wanna make an array of protocols? How that would make sense with JSONModel?

**Comment by mr-const** [comment]
Of course I did, you even can look into exact sample: https://github.com/icanzilb/JSONModel#model-collections

**Comment by Anupdas** [comment]
If you have want to convert a list of models use,

```objc
NSArray *modelArray = [ResponseEntityList arrayOfModelsFromDictionaries:jsonArray];
```

**Comment by billinghamj** [comment]
Use one of the following methods:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
- `+arrayOfModelsFromString:error:`
