### ISSUE TITLE
mergeWithDictionary fails silently

### ISSUE THREAD

**Issue by pbassut** [icanzilb/JSONModel#305]
So, I just spent some minutes(almost half an hour) trying to use mergeWithDictionary because I found more elegant to not create another object.

The problem was I forgot to ignore a delegate that was inside my model which lead me to the bug.

At the moment, mergeWithDictionary does not let the user provide a NSError pointer to notify the user in case something bad occurs.

I think mergeWithDictionary should have two versions: One that receives an error pointer and one that does not.

That way, if the user doesn't wanna know if the merge happened correctly(because he's just adding stuff that would be nice to have - Can't think of a use case like that) he won't pass an error pointer. Otherwise, well...

Note that I think this should be a feature because the developer should know if their keys mapped to the wrong stuff or it didn't match at all.

**Comment by billinghamj** [comment]
Agreed! Fixed in f472318dbf6d115a5aa1b40c66c0722233760b97 :)
