### ISSUE TITLE
Coredata integration

### ISSUE THREAD

**Issue by BadChoice** [icanzilb/JSONModel#306]
Is there any way to quick work with core data? I mean saving models to coredata and loading them from there as well

**Comment by haitham-aboshahba-sociomantic** [comment]
+1, would be great addition

**Comment by haitham-reda** [comment]
+1 would be a great addition

**Comment by Mozilla9** [comment]
Magicalrecord solves this problem. Use a data import.

**Comment by billinghamj** [comment]
There is a branch on JSONModel for CoreData - https://github.com/icanzilb/JSONModel/tree/coredata

I'm not sure what its status is though.

**Comment by icanzilb** [comment]
the core data branch was abandoned - it increases the lib complexity so much that I didn't want to pursue it further. however I decided to leave the branch in if anyone wants to dig in and check the approach I wanted to introduce

**Comment by billinghamj** [comment]
Okey dokey, makes sense. CoreData does seem to be quite the beast to work with from what I've seen/heard.

**Comment by icanzilb** [comment]
@Mozilla9 do you have a link to a gist or something that shows how to use magicalrecord with jsonmodel? this could be a nice addition to this repo's readme

**Comment by Mozilla9** [comment]
@icanzilb Hi. See [https://gist.github.com/Mozilla9/c8d62f5cf0fffa81300c](https://gist.github.com/Mozilla9/c8d62f5cf0fffa81300c).

**Comment by icanzilb** [comment]
cool thanks :) I'll have a look
