### ISSUE TITLE
how to convert field to custom type field?

### ISSUE THREAD

**Issue by hengchengfei** [icanzilb/JSONModel#307]
I want to do with the follow logic.

if(rent_type==0)
{
rentType=@"xx";
} else{
rentType=@"yy";
}

for example:
--------------------------------------------------------
//json value
@property(nonatomic)int rent_type;

//Ignore field
@property(nonatomic)NSString* rentType;
--------------------------------------------------------

http json value
--------------------------------------------------------
 {
"type":0
}
--------------------------------------------------------

**Comment by Anupdas** [comment]
Please refer my answer #314 and kindly refrain from raising same issues.
