### ISSUE TITLE
JSONModel not working when running from Test Cases

### ISSUE THREAD

**Issue by karmn92** [icanzilb/JSONModel#310]
I have ```Members``` object with array of ```Member``` 

```
#import "JSONModel.h"
#import "Member.h"
#import "Account.h"

@protocol Members <NSObject>
@end

@interface Members : JSONModel
@property(strong,nonatomic) NSMutableArray <Member> *members;
```

```Member``` class has an array of ```Account```
```
#import <Foundation/Foundation.h>
#import "Account.h"
#import "JSONModel.h"

@protocol Member <NSObject>
@end

@interface Member : JSONModel
@property(nonatomic) NSMutableArray<Account>* accounts;
@end
```

Here's the part which causes issue
```
 NSError *err;
 _members = [[Members alloc] initWithDictionary:response error:&err];
```
This JSONModel call works fine when I build my code normally. The _members object is created with all the internal objects, well parsed.
But when I run it from the UnitTest file I get an error and the internal objects are not parsed i.e. Members class gets shown as dictionary but Member and Accounts are not parsed. Error description is following -
```
[0] = <error: expected ']'
error: 1 errors parsing expression
```

**NOTE: I am using XCUnitTestCase and this implementation is in PhoneGap.**

**Comment by billinghamj** [comment]
Is this issue still persisting?

From the error, it sounds as though the `]` character which marks the end of an array may be missing.
