### ISSUE TITLE
Does not work with App Extension

### ISSUE THREAD

**Issue by Urkman** [icanzilb/JSONModel#311]
JSONModel does not work in an App Extension (WatchKit).
Because it uses [UIApplication sharedApplication].

Error:
'sharedApplication' is not available on iOS (App Extension)

**Comment by icanzilb** [comment]
yeah it looks like I'll have to remove that line in the next update - it's been causing too much trouble

**Comment by Urkman** [comment]
I see, that somebody already fixed this.
So I created a Pull Request for this fix...

**Comment by billinghamj** [comment]
This has been resolved.
