### ISSUE TITLE
return custom result?

### ISSUE THREAD

**Issue by hengchengfei** [icanzilb/JSONModel#314]
for example:
json:
  {
  "type":0
  }

model:
@property(nonatomic,strong)NSString<Optional>* type;

I want to do the follow's logic:
if(json.type==0){
  model.type = @"xxx";
}else{
  model.type = @"yyy";
}

**Comment by Anupdas** [comment]
You can define your own custom setter and getter
```objc


- (void)setTypeWithNSNumber:(NSNumber *)type{
    self.type = [type integerValue] == 0 ? @"xxx" : @"yyy";
}

- (id)JSONObjectForType{
    return [self.type isEqualToString:@"xxx"] ? 0 : 1;
}

```

**Comment by billinghamj** [comment]
You can now also define multiple custom setters.
