### ISSUE TITLE
Custom transformer for CLLocationCoordinate2D?

### ISSUE THREAD

**Issue by guilhermearaujo** [icanzilb/JSONModel#316]
I was trying to implement a custom transformer for CLLocationCoordinate2D based on [CGStructs Transformers](https://github.com/JSONModel/CGStructs_Transformers).

The JSON I am working with provides a coordinate like this:

```json
{
  "location": {
    "longitude": -73.769264,
    "latitude": 47.699343
  }
}
```

I tried writing this transformer:

```obj-c
- (CLLocationCoordinate2D)CLLocationCoordinate2DFromNSDictionary:(NSDictionary *)dictionary {
  return CLLocationCoordinate2DMake([dictionary[@"latitude"] doubleValue],
                                    [dictionary[@"longitude"] doubleValue]);
}
```

But after I check that the method would never be called (and the fact that the app crashes), I noticed that when JSONModel try to look up a custom transformer, it attempts to find a selector called `{FromNSDictionary:`. Since a method with that name is impossible, what I was doing would definitely never work.

So is it possible to work with CLLocationCoordinate2D or should I just quit and write a custom class (or any of the other workarounds)?

**Comment by ab-rdarts** [comment]
Same problem here. Any solution without using CLLocation class?

**Comment by icanzilb** [comment]
What is the type of your property? this looks like a bug

**Comment by ab-rdarts** [comment]
CLLocationCoordinate2D

**Comment by icanzilb** [comment]
yeah, defo looks like a bug - it kind of depends what the objc runtime returns as the encoded type of the property, can't tell you more without debugging a class with this property ... I think for now you need to add custom code to parse the location

**Comment by ab-rdarts** [comment]
I see that it recognized such json as struct in the following code

```
else if ([scanner scanString:@"{" intoString: &propertyType]) {
                [scanner scanCharactersFromSet:[NSCharacterSet alphanumericCharacterSet]
                                    intoString:&propertyType];
                
                p.isStandardJSONType = NO;
                p.structName = propertyType;

            }
```
and it's used here:

```
 NSString* selectorName = [NSString stringWithFormat:@"%@From%@:",
                                              (property.structName? property.structName : property.type), //target name
                                              sourceClass]; 
```

and as a result selectorName is

```
{FromNSDictionary
```

**Comment by ab-rdarts** [comment]
propertyAttributes is equal to T{?=dd},N,V_coordinate

**Comment by ab-rdarts** [comment]
as I understand the reason CLLocationCoordinate2D is unnamed struct which defined as
```
typedef struct {
	CLLocationDegrees latitude;
	CLLocationDegrees longitude;
} CLLocationCoordinate2D;
```
instead of 
```
typedef struct CLLocationCoordinate2D {
	CLLocationDegrees latitude;
	CLLocationDegrees longitude;
} CLLocationCoordinate2D;
```

**Comment by icanzilb** [comment]
ha! this looks like the real problem here ...

**Comment by ab-rdarts** [comment]
maybe for such cases it should be like this inside __inspectProperties
```
                p.isStandardJSONType = NO;
                p.structName = propertyType;

                if ( [propertyType isEqualToString:@"{"] ) {
                    p.structName = p.name;
                }
```

**Comment by icanzilb** [comment]
well I guess you can always create a name based transformer?

**Comment by icanzilb** [comment]
eg. -(void)setLocationWithNSDictionary(dict: NSDictionary) if your property is called "location"

**Comment by ab-rdarts** [comment]
oh, thanx, you are right. It seems I missed custom data transformers topic.

**Comment by billinghamj** [comment]
Yep, custom getters & setters are definitely the way to go here. Just implement these methods on your model:

- `- (NSDictionary *)JSONObjectForLocation`
- `- (void)setLocationWithNSDictionary:`

**Comment by icanzilb** [comment]
@ab-rdarts - there's an example for writing custom transformers here: https://github.com/JSONModel/CGStructs_Transformers

**Comment by cachly** [comment]
@ab-rdarts @guilhermearaujo @icanzilb Was there a solution to this? I am running into this exact issue.
