### ISSUE TITLE
Object without key

### ISSUE THREAD

**Issue by partho-maple** [icanzilb/JSONModel#318]
Hi,

I have a json string like the following...

[{
        "date": 1429145400000,
        "hours": 0
    }, {
        "date": 1429162400000,
        "hours": 0
    }, {
        "date": 1429122400000,
        "hours": 0
    }, {
        "date": 1429142400000,
        "hours": 13.0
    }, {
        "date": 1429228800000,
        "hours": 11.0
    }, {
        "date": 1429315200000,
        "hours": 10.3333
    }, {
        "date": 1429401600000,
        "hours": 8.8333
}]

Clearly the json object will be an NSArray. But it has no parent key to create and parse array object. So how i am supposed to create an parse array object from that json string ? Please someone help me out.

Thanks.

**Comment by Ra1G1** [comment]
Just make a JSONModel with two properties "date" and "hours" and add each model created in a NSMutableArray by looping above array

**Comment by Anupdas** [comment]
As suggested by @Ra1G1 you could create a JSONModel subclass with date and hours. 

```objc
#import "JSONModel.h"

@interface DateModel : JSONModel

@property (strong, nonatomic) NSDate *date;
@property (assign, nonatomic) float hours;

@end

@implementation DateModel

- (void)setDateWithNSNumber:(NSNumber *)dateNumber{
    self.date = [NSDate dateWithTimeIntervalSince1970:dateNumber.doubleValue/1000];
}

- (id)JSONObjectForDate{
    NSTimeInterval interval = [self.date timeIntervalSince1970];
    return @(interval*1000);
}

@end
```

Instead of enumerating the array use
``` objc
    NSArray *array = //array of dictionaries
    NSArray *models = [DateModel arrayOfModelsFromDictionaries:array];
```

The models can be exported to json as

```objc
NSArray *array = [DateModel arrayOfDictionariesFromModels:models];
//Serialize this array
```

**Comment by billinghamj** [comment]
To import, use one of the following methods:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
- `+arrayOfModelsFromString:error:`
