### ISSUE TITLE
Changing properties of a model after init

### ISSUE THREAD

**Issue by brownpixel** [icanzilb/JSONModel#325]
Quick question

I'm seeing some odd behavior when i change a property after an instance of a jsonmodel class has been initialized. Specifically in the form of deallocation
for example:

```
NSError *err;
ExModel *model = [[ExModel alloc] initWithString:[defaults objectForKey:ARG_MODEL] error:&err];
model.dude = @"hey there";
```

if i try to do anything with the instance of the model after that (i.e export it to json string or dictionary) I get a [CFString retain]: message sent to deallocated instance error...So my question is are these json model's properties not meant to be changed after they have been initialized?

**Comment by sauvikatinnofied** [comment]
This problem should not appear, will you please post the content of the ExModel.h and ExModel.m?

**Comment by sauvikatinnofied** [comment]
Content of the ProductJSON.json
{
    "id": "123",
    "name": "Product name",
    "price": 12.95
}




// Override point for customization after application launch.
    NSString *jsonFilePath = [[NSBundle mainBundle] pathForResource:@"ProductJSON" ofType:@"json"];
    NSError *fileReadError;
    NSString *jsonString = [NSString stringWithContentsOfFile:jsonFilePath encoding:NSUTF8StringEncoding error:&fileReadError];
    if (!fileReadError) {
        NSError *jsonParsingError;
        Product *newproduct = [[Product alloc] initWithString:jsonString error:&jsonParsingError];
        if (!jsonParsingError) {
            // Changing the name of the product
            newproduct.name = @"Sweet bytes";
            NSLog(@"newproduct after model property changed: %@", [newproduct toJSONString]);
        }else{
            NSLog(@"JSON Parsing Error: %@", jsonParsingError.localizedDescription);
        }
    }else{
        NSLog(@"File read error occurs while reading %@ ERROR:%@", jsonFilePath, fileReadError.localizedDescription);
    }



// And this is the log from console
newproduct after model property changed: {"id":"123","name":"Sweet bytes","price":12.95}

**Comment by brownpixel** [comment]
Sure

ExModel.h content:
#import "JSONModel.h"

@interface ExModel : JSONModel
@property (strong, nonatomic) NSString *firstName;
@property (strong, nonatomic) NSString *lastName;
@property (strong, nonatomic) NSString *dude;

@end

ExModel.m content:
#import "ExModel.h"
@implementation ExModel
@end


hmm maybe its because i'm executing the block of code in a function that is executed after receiving an nsnotification?

**Comment by sauvikatinnofied** [comment]
Yes, this might be an issue. Use proper breakpoint to find out the cause of that problem. In my test project it worked perfectly. You can have a look on the project over here https://github.com/sauvikatinnofied/JSONModelIssue325.

**Comment by brownpixel** [comment]
After I call [model toJSONString] it happens specifically on line 952 in the JSONModel.m file for the function:
```
-(NSDictionary*)toDictionaryWithKeys:(NSArray*)propertyNames
``` 

I even put logger to see on which property i get the [CFString retain] error message , and its the property i changed i.e the dude property

**Comment by brownpixel** [comment]
Nevermind...one of the NSString properties on my model was assigning rather than using a strong reference, which would cause the deallocation... :)
