### ISSUE TITLE
@throw and NSAssert

### ISSUE THREAD

**Issue by happyingly** [icanzilb/JSONModel#326]
Could you add some macro definitions for @throw and NSAssert for DEBUG

Because I could not hope it come into force in 'Release'. 

Thank U very much.

**Comment by icanzilb** [comment]
What kind of macro definitions there should be and what the result will be? I'm not sure I understand

**Comment by happyingly** [comment]
Like this:

#ifdef DEBUG
   @throw [NSException exceptionWithName:@"Type not allowed"
                                                       reason:[NSString stringWithFormat:@"%@ type not supported for %@.%@", property.type, [self class], property.name]
                                                     userInfo:nil];
#endif

**Comment by icanzilb** [comment]
and what is the desired outcome of this? Can you tell me what do you want to achieve?

**Comment by billinghamj** [comment]
JSONModel returns error information via error pointers. If you want to throw exceptions or make assertions when (de)serialization errors happen, you should do so in your own code. This is not something JSONModel would do by default, because (de)serialization errors are not exceptional.
