### ISSUE TITLE
NSData uploading with progress with JSONHTTPClient

### ISSUE THREAD

**Issue by sauvikatinnofied** [icanzilb/JSONModel#327]
No doubt, JSONHTTPClient has simplified our network requests so simple without using AFNetworking.
Today I was searching a method in which I will be able to send NSData with the following format
{
  "attachment" : image dada
} ,
 but could not find any available method which will upload image data with progress handler. It is possible to provide such facility in this light weight HTTPClient?

**Comment by billinghamj** [comment]
Probably not, I'm afraid. JSONHTTPClient is designed to remain simple. You'd be best using another networking library.
