### ISSUE TITLE
How can i covert NSString to object ?

### ISSUE THREAD

**Issue by cwnga** [icanzilb/JSONModel#330]
How can i covert NSString to object ?

@interface Seller: JSONModel
@property (strong, nonatomic) NSString *id;

@interface listing: JSONModel
@property (strong, nonatomic) NSString *price;
@property (strong, nonatomic) Seller *seller;

and listings is 
{
    "price": 1,
    "sellerId" : "xxxxx";
}

i want to convert sellerId to Seller object , 
how can i do ?

**Comment by sauvikatinnofied** [comment]
You need to overwrite ```- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError *__autoreleasing *)err``` of ```listing``` as follows

```objective-c
- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError *__autoreleasing *)err{
    if (self = [super initWithDictionary:dict error:err]) {
      _ seller = [[Seller alloc] init];
      _seller.id = [dict objectForKey:@"sellerId"];
    }
    return self;
}
```

Hope this will work, please let me know, whether it is working or not.

**Comment by cwnga** [comment]
@sauvikatinnofied  thanks for your help , it work !

**Comment by cwnga** [comment]
i think if keyMapper can set this, i think it is better :)

**Comment by sauvikatinnofied** [comment]
I think JSONModel only maps dictionary/JSONString to JSONModel class type objects. It can not directly map a simple string to a JSONModel object.

**Comment by icanzilb** [comment]
@cwnga  you can write a custom value transformer that converts NSString to Seller, read this tutorial http://code.tutsplus.com/tutorials/beyond-the-basics-of-jsonmodel--cms-20731 pay attn to section 7 "Custom Data Transformations"
