### ISSUE TITLE
By-reference parameter types should be __autoreleasing

### ISSUE THREAD

**Issue by vocaro** [icanzilb/JSONModel#331]
As described in Apple's [Transition To ARC](https://developer.apple.com/library/mac/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html) documentation, parameters passed by reference should be marked __autoreleasing to avoid generating an extra variable.

JSONModel's initWithDictionary and initWithData do not follow this recommendation. Their NSError parameters should be changed from this:

    (NSError **)

to this:

    (NSError * __autoreleasing *)

**Comment by icanzilb** [comment]
I missed that, will look into it

**Comment by billinghamj** [comment]
I'm not sure this needs to be explicitly added. See:

- http://clang.llvm.org/docs/AutomaticReferenceCounting.html#indirect-parameters
- http://stackoverflow.com/a/15487196

Seems to me that it is implicit in these cases?
