### ISSUE TITLE
Cookies handling with JSONHTTPClient

### ISSUE THREAD

**Issue by sauvikatinnofied** [icanzilb/JSONModel#334]
I my current project I am using _```+(void)postJSONFromURLWithString:(NSString*)urlString params:(NSDictionary*)params completion:(JSONObjectBlock)completeBlock;```_ method to create account and log in my application for the very first time . For secound and onwards, log in call is not there, application directly opens the user's profile screen. But when I am updating user profile (name, contact number etc.), I am getting response status code 403 from by the statement 
```objective-c
 NSLog(@"Response status code = %i", (int)response.statusCode);
```
added in implementation of method
```objective-c
+(NSData*)syncRequestDataFromURL:(NSURL*)url method:(NSString*)method requestBody:(NSData*)bodyData headers:(NSDictionary*)headers etag:(NSString**)etag error:(JSONModelError**)err
```

403 is generally invoked due to authorization failure in server side. 
Is there any way to see what are the cookies are going to server side while I am making an API call with _```+(void)postJSONFromURLWithString:(NSString*)urlString params:(NSDictionary*)params completion:(JSONObjectBlock)completeBlock;```_?

**Comment by billinghamj** [comment]
You could MITM the requests to check the headers being sent. http://mitmproxy.org does this wekk

**Comment by billinghamj** [comment]
Also, as usual, JSONHTTPClient is designed to provide a very simple implementation. So for more complex use cases, probably best to go for another networking library.
