### ISSUE TITLE
NSUUID not supported

### ISSUE THREAD

**Issue by aie0** [icanzilb/JSONModel#335]
When having property of type UUID, serialization throws an exception

@property (nonatomic) NSUUID *uuid;

*** Terminating app due to uncaught exception 'Value transformer not found', reason: '[JSONValueTransformer __JSONObjectFromNSUUID:] not found'

Expected behavior would be to use [uuid UUIDString] method.

**Comment by icanzilb** [comment]
the error message clearly says that you did not create a method to convert a UUID to a string. if you don't know how to write a custom value transformer read up this tutorial: http://code.tutsplus.com/tutorials/beyond-the-basics-of-jsonmodel--cms-20731
