### ISSUE TITLE
NSDictionary containing NSArrays of JSONModel classes

### ISSUE THREAD

**Issue by forevercamecrashing** [icanzilb/JSONModel#336]
I need to serialize an NSDictionary where the keys are NSStrings and the objects are NSArrays.  I can get this to work when the NSArrays contain NSString objects, but when I try to put any of my JSONModel classes in the arrays it won't work.

Is this possible?

For the moment I'm using a workaround where I serialize each of my JSONModel classes to string individually before putting them in the arrays, but this isn't ideal...

**Comment by huadee** [comment]
me too

**Comment by Anupdas** [comment]
JSONModel supports serialization of complex type collection. 

* Create subclasses of JSONModel
```objc
@interface CustomSubModel : JSONModel
```
* Declare an empty protocol with the same name of subclass

```objc
@protocol CustomSubModel
@end
```
* Make the collection implement the protocol. 

```objc
@property (strong , nonatomic) NSArray<CustomSubModel> *arrayOfSubModels;
```
