### ISSUE TITLE
JSON Polymorphism 

### ISSUE THREAD

**Issue by carrascoacd** [icanzilb/JSONModel#339]
There is a way to support "JSON Polymorphism"?
Something like this http://wiki.fasterxml.com/JacksonPolymorphicDeserialization

**Comment by nikmis** [comment]
There doesn't seem to be a direct support for this in JSONModel. But you can do using custom setters as shown here.
https://github.com/icanzilb/JSONModel/issues/213
If you are using Jackson, then you should be able to include Class type in your JSON. During JSON deserialization, you can override your setter to look at the class string in the JSON dictionary passed, and create appropriate Objective C classes.

**Comment by billinghamj** [comment]
Create a class cluster. See - https://github.com/icanzilb/JSONModel/issues/229#issuecomment-52556421
