### ISSUE TITLE
Impact of iOS 9 Objective C generics.

### ISSUE THREAD

**Issue by nikmis** [icanzilb/JSONModel#341]
iOS 9 adds lightweight support for generics in Objective C, and the syntax is very similar to JSONModel's array/dictionary serialization.
```
@property NSArray<NSDate *>* dates;
@property NSSet<NSString *>* words;
```

https://developer.apple.com/library/prerelease/watchos/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html

Do you know what impact this will have on JSONModel ? Is it compatible ?

**Comment by icanzilb** [comment]
Didn't have the chance to try it just yet - still to come back from SF. My best guess is that it'll all just work because NSArray takes a pointer type and JSONModel uses protocols.

**Comment by billinghamj** [comment]
The issue with the new generics is that the angle brackets cannot contain both types and protocols.

iOS 9 also supports nullability however:

```objc
@property (nullable) NSArray<NSDate *> *dates;
@property (nonnull) NSSet<NSString *> *words;
```

Equivalent to this:

```objc
@protocol NSDate;

@property NSArray<NSDate, Optional> *dates;
@property NSSet *words;
```

The question is whether JSONModel is able to get the nullable/nonnull and generics from the obj-c runtime.

**Comment by billinghamj** [comment]
Unfortunately, as per the info provided at WWDC, it sounds like the answer is no:

Generics: http://stackoverflow.com/a/30866503

Property attributes: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtPropertyIntrospection.html#//apple_ref/doc/uid/TP40008048-CH101-SW5

**Comment by icanzilb** [comment]
I'll put in some time to experiment with those during summer, although all those changes sound like compile time optimizations and I don't think I can access them from the ObjC runtime...

**Comment by nikmis** [comment]
Hi Marin, were you able to test this out ?

**Comment by xilin** [comment]
Hi @icanzilb, how's going on?

**Comment by tounaobun** [comment]
+1

**Comment by billinghamj** [comment]
They are compile time checks. They do not exist in the runtime.

However, I have found that they can all coexist with JSONModel. It doesn't result in the cleanest code, but it's reasonable enough.

e.g.:

```objc
@protocol NSDate;

@property (nonatomic, strong, nullable) NSArray<NSDate *> <NSDate, Optional> *dateArray;
@property (nonatomic, strong, nonnull) NSSet <NSDate *> <NSDate> *dateSet;
@property (nonatomic, strong, nullable) NSDictionary <NSString *, id> <Optional> *dict;
```

So for nullability:

```objc
// optional/nullable
@property (nullable) id <Optional> propertyName;

// required/nonnull
@property (nonnull) id propertyName;
```

For 'generics':

```objc
@protocol MyType;

// array/set
@property NSArray <MyType *> <MyType> *propertyName;

// dictionary
@property NSDictionary <NSString *, MyType *> <MyType> *propertyName;
```

Note with the 'generics' notation, the new Obj-C syntax must come before the protocols and must be in separate angle-brackets.

**Comment by billinghamj** [comment]
It might be possible to simplify this with some kind of preprocessor macro system though. e.g.:

```objc
JMPROP(propA, NSString);
JMPROP_OPT(propB, NSString);
JMPROP_GEN(propC, NSArray, MyType);
JMPROP_GEN_OPT(propD, NSDictionary, MyType);
```

Equivalent to:

```objc
@property (nonatomic, strong, nonnull) NSString *propA;
@property (nonatomic, strong, nullable) NSString <Optional> *propB;
@protocol MyType;
@property (nonatomic, strong, nonnull) NSArray<MyType *> <MyType> *propC;
@protocol MyType;
@property (nonatomic, strong, nullable) NSDictionary<NSString *, MyType *> <MyType, Optional> *propD;
```

**Comment by xilin** [comment]
@billinghamj It looks acceptable to support the type checking feature. Thanks!
