### ISSUE TITLE
how to fetch the NSArray<User>

### ISSUE THREAD

**Issue by adeewu** [icanzilb/JSONModel#344]
## I have json data like:
```json
[
    {"id": 1, "name": "jim"},
    {"id": 2, "name": "lovy"}
]
```
## how can I fetch the NSArray\<User\> object from Internet

**Comment by SunsetGlow** [comment]
You can do it like this:
NSArray *array = (NSArray *)[[JSONModelArray alloc] initWithArray:dictionaryObject modelClass: [User class]];

dictionaryObject is a NSDictionary object and you should convert the JSON String to NSDictionary object to use the initWithArray:modelClass: method.

**Comment by adeewu** [comment]
@SunsetGlow i know this way. but now, the json data is `remote data`. i want to do like this 
> [[User alloc] initFromURLWithString:urlString completion:^block ]

**Comment by sauvikatinnofied** [comment]
Create a class `RemoteUsers` subclassing `JSONModel` as it's parent class.

`RemoteUsers.h`
```objective-c
#import "JSONModel.h"
#import "User.h"

@interface RemoteUsers : JSONModel
@property (nonatomic, strong) NSArray* <User>users;
@end

```
and `RemoteUsers.m`
```objective-c
#import "RemoteUsers.h"
@implementation RemoteUsers

@end

```
Now from where you want populate data from remote server import `#import "JSONHTTPClient.h"` and `#import "RemoteUsers.h"` using the following code

```objective-c
    
    [JSONHTTPClient getJSONFromURLWithString:@"PathToRemoteJSON" params:nil completion:^(id json, JSONModelError *err) {
        NSError *jsonParsingError ;
        
        RemoteUsers *remoteUsers = [[RemoteUsers alloc]initWithDictionary:json error:&jsonParsingError];
        if (!jsonParsingError) {
            //remoteUsers.users holds the array of the users
        }else{
            NSLog(@"ERROR WHILE FETCHING USERS FROM REMOTE SERVER %@", jsonParsingError.localizedDescription);
        }
    }];
```

**Comment by aprofromindia** [comment]
Is there a way to ConvertOnDemand for API responses like this one ?

**Comment by billinghamj** [comment]
You should not directly initialize the `JSONModelArray` class.

Instead you should use something like:

```objc
NSError *error;
NSArray *array = [User arrayOfModelsFromString:jsonString error:&error];
```

**Comment by billinghamj** [comment]
@adeewu You could try using `JSONHTTPClient`.
