### ISSUE TITLE
multiple custom setter methods for different data types

### ISSUE THREAD

**Issue by jackieyk** [icanzilb/JSONModel#345]
I use custom setter to init special property in my JSONModel class.
for example, 
@property (strong, nonatomic) NSMutableArray < OrderPointModel > *point_list;
The OrderPointModel is JSONModel subclass too.

But the data for the property I get from server is not a JSON but a string:
{
	...
	"point_list" = "[{\"date\":20150619,\"bill\":5,\"express\":2,\"order\":12},{\"date\":20150620,\"bill\":1,\"express\":0,\"order\":2},{\"date\":20150625,\"bill\":24,\"express\":7,\"order\":47}]";
}
so I need to convert the string to dictionary in my custom setter method:

 -(void)setPoint_listWithNSString:(NSString *)point_list {
    NSArray *pointArray = [NSJSONSerialization JSONObjectWithData:[point_list   dataUsingEncoding:NSUTF8StringEncoding] options:NSJSONReadingMutableContainers error:nil];
...
}

The problem is: I also need to init the model by cached data, and the point_list in cached data is an array but not a string. so app will crash in the custom setter.
I have to identify whether the point_list is kind of string in the custom setter now, the code looks ugly.

So I think can you support multiple custom setter methods?
Then in my code, I just need to add one more method like:
-(void)setPoint_listWithNSArray:(NSArray *)point_list {
...
}
Thanks.

**Comment by jackieyk** [comment]
any update?

**Comment by Anupdas** [comment]
You could create a custom getter which will serialise the ```point_list``` back to string. That way you could prevent the hazzle to check.

```obj
- (id)JSONObjectForPoint_list{
    NSArray *array = [OrderPointModel arrayOfDictionariesFromModels:self.point_list];
    NSString *jsonString = //Serialize array to string
    return jsonString;
}
```

 Other solution would be to check if the string is a valid json 
```objc
[NSJSONSerialization isValidJSONObject:json]
```

**Comment by billinghamj** [comment]
+1 to this. Currently the first setter to be looked up will be used. This should be changed to a dictionary of setters for each data type.

**Comment by billinghamj** [comment]
PR #412 should resolve this @jackieyk.

**Comment by jackieyk** [comment]
thanks
