### ISSUE TITLE
How to cancel request in JSON Model?

### ISSUE THREAD

**Issue by bobongski** [icanzilb/JSONModel#347]
How to cancel request in JSON Model?

**Comment by billinghamj** [comment]
I'm assuming that you're using `JSONHTTPClient`.

JSONModel's built-in request methods are designed to be very simple and basic. They don't cater for more complex use-cases.

If you'd like more control over the request-making process, the best thing to do is to use a more comprehensive networking library to make the request, before deserializing with JSONModel. Examples of good networking libraries are NSURLSession and AFNetworking.
