### ISSUE TITLE
Getting Segmentation Problem in `-(NSDictionary*)toDictionaryWithKeys:(NSArray*)propertyNames`

### ISSUE THREAD

**Issue by sauvikatinnofied** [icanzilb/JSONModel#349]
In my current application, I am converting a `JSONModel` object to JSON string calling `toJSONString`.
But the application crashes, in the line number 953 with the statement `value = [self valueForKey: p.name];` in `JSONModel.m` file. Getting a error like 

`Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x447ca811
Crashed Thread:  0`.

**Comment by billinghamj** [comment]
Sounds like JSONModel may think a property exists which actually doesn't. Could you provide samples of the models & JSON causing this?

**Comment by billinghamj** [comment]
Closed due to 2 weeks of inactivity - open a new issue if you still need help with this.
