### ISSUE TITLE
Ignoring https certificate errors with  sendSynchronousRequest

### ISSUE THREAD

**Issue by mekicim** [icanzilb/JSONModel#350]
I have fixed like this for https request 
 I'd recommend adding in your code for https request errors.

    //added this line 
    [NSURLRequest setAllowsAnyHTTPSCertificate:YES forHost:[url host]];
    
    //fire the request
	NSData *responseData = [NSURLConnection sendSynchronousRequest: request
                                                 returningResponse: &response
                                                             error: err];
    //convert an NSError to a JSONModelError

	////////add header like this 
	NSURLRequest+IgnoreSSL.h
	@interface NSURLRequest (IgnoreSSL)
	
	+ (BOOL)allowsAnyHTTPSCertificateForHost:(NSString*)host;
	+ (void)setAllowsAnyHTTPSCertificate:(BOOL)allow forHost:(NSString*)host;
	
	@end

**Comment by csamzhou** [comment]
```
setAllowsAnyHTTPSCertificate:forHost:
```
is a private api method, this will be reject by the review team.
