### ISSUE TITLE
how to handle statusCode with JSONHttpClient

### ISSUE THREAD

**Issue by adeewu** [icanzilb/JSONModel#353]
#### I have a remote resource, when the http response is:
**`statusCode=200` the response data is**
```json
{
  "a": "the statusCode 200 string"
}
```
**`statusCode=201` the response data is**
```json
{
  "b": "the statusCode 201 string"
}
```

how to handle the statusCode with JSONHttpClient???
can add statusCodeBlock param to handle it in `getJSONFromURLWithString`?

> +(void)getJSONFromURLWithString:(NSString*)urlString params:(NSDictionary*)params completion:(JSONObjectBlock)completeBlock `statusCode:(StatusCodeBlock) codeBlock`

**Comment by billinghamj** [comment]
JSONHttpClient doesn't expose the status code. You should try using a more comprehensive library for the networking part of your code - e.g. NSURLSession or AFNetworking.
