### ISSUE TITLE
Swift Compatibility of  -(instancetype)initWithString:(NSString *)string usingEncoding:(NSStringEncoding)encoding error:(JSONModelError**)err;

### ISSUE THREAD

**Issue by sauvikatinnofied** [icanzilb/JSONModel#354]
I am currently facing problem while accessing  
`  -(instancetype)initWithString:(NSString*)string error:(JSONModelError**)err;` initializer in swift.

I am seeing the initializer has been ported to  `init!(string: String!, error err: AutoreleasingUnsafeMutablePointer<JSONModelError?>)`

I am using the following code snippet to initialize the object
```swift
        var userInfoJSONParsingError: NSError?       
        var userInfo = GFTeamMemberUserInfo(string: userInfoKey, error:& userInfoJSONParsingError)
```
But it is showing me error `Cannot find an initializer for type 'GFTeamMemberUserInfo' that accepts an argument list of type '(string: String, error: inout NSError?)`.

How to call this initializer?

**Comment by pjebs** [comment]
I got the same problem. Did you solve it?

**Comment by pjebs** [comment]
It would be nice if there was some way for Marin to make it port to Swift with the throws syntax like the other JSONModel initializers.

**Comment by sauvikatinnofied** [comment]
Anyway I did, but there is not anyway to trace any modelling error while creating objects. Try this one 

```swift
let myModel = <MyJSONModelClass>(string: jsonResponseInString, error: nil)
```
Please let me know if you have any idea to trace the error.

**Comment by pjebs** [comment]
My solution is:

1) Convert String to NSData
`
let d = <STRING>.dataUsingEncoding(NSUTF8StringEncoding)
`

2) Then use NSData initializer:

`
let m = try JSONModel(data: d!)
`

**Comment by pjebs** [comment]
it's not ideal but it works.
I have no idea why the String version of the initializer bridges over as AutoreleasingUnsafeMutablePointer<JSONModelError?>

**Comment by billinghamj** [comment]
Does it make any difference if you declare the type of `userInfoJSONParsingError` as `JSONModelError?`

**Comment by billinghamj** [comment]
Closed due to 2 weeks of inactivity - open a new issue if you still need help with this.
