### ISSUE TITLE
Is there some way use key map like this?

### ISSUE THREAD

**Issue by cuzv** [icanzilb/JSONModel#355]
```
{
    "warehouse_id" : "0",
    "warehouse_name" : null,
    "settlementInfo" : {
        "priceTotal" : 138,
        "freeFreightCond" : 199
      }
}
```

=>

```
{
    "warehouse": {
        "warehouse_id" : "0",
        "warehouse_name" : null    
    },
    "settlementInfo" : {
        "priceTotal" : 138,
        "freeFreightCond" : 199
     }
}
```

**Comment by iOSCuriosity** [comment]
@cuzv You may create "warehouse" JSONModel which includes "warehouse_id" and "warehouse_name".
Same like above, you may also create "settlementInfo" JSONModel which includes "priceTotal" and "freeFreightCond".
After that you may create additional "Parent" JSONModel which includes "warehouse" and "settlementInfo" as its property.
e.g.,

In ICWareHouse.h,

@interface ICWarehouse : JSONModel

@property (nonatomic, strong) NSString *warehouseId;
@property (nonatomic, assign) id warehouseName;

@end

In ICWarehouse.m

leave it as it is. [Blank]

In ICSettlementInfo.h

@interface ICSettlementInfo : JSONModel

@property (nonatomic, assign) double priceTotal;
@property (nonatomic, assign) double freeFreightCond;

@end

In ICSettlementInfo.m

leave it as it is. [Blank]

In ICJSON.h

@class ICSettlementInfo, ICWarehouse;

@interface ICJSON : JSONModel

@property (nonatomic, strong) ICSettlementInfo *settlementInfo;
@property (nonatomic, strong) ICWarehouse *warehouse;

+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dict;
@end

**Comment by cuzv** [comment]
@iOSCuriosity Thanks First!
But I am afraid what you told is not I am asking!
I wanna know is it possible to use the upper structure from server end response as the down structure method in client model.
What you told me is actually just use the "correct" data structure ORM.

**Comment by billinghamj** [comment]
No, I'm afraid the key mapping system doesn't work this way.

You'd probably be best making models representing exactly what comes back from the server, then adding a method which transforms an instance of the server class into an instance of the class with another structure.
