### ISSUE TITLE
Extending JSONModel subclass object

### ISSUE THREAD

**Issue by justme1** [icanzilb/JSONModel#358]
Hi,

I would like to hear from you how you handle the following scenario:

In my project all the network objects are deserialized using JSONModel. Some of these objects need to be extended - I need to add several properties which I don't get from the server, rather the client is responsible to get and set these properties.

My question where would you add these additional properties? Would you addd them to the object, would you subclass and add properties there, or maybe use composition instead?

Thanks!

**Comment by iOSCuriosity** [comment]
@justme1  I think you may add those additional properties in your JSONModel object and mark them <Ignore>. After composition of that object you can add those ignored properties by yourself.

**Comment by billinghamj** [comment]
You should put the additional properties directly on your model. Just make sure to mark them as ignored.

e.g.:

```
@interface MyModel : JSONModel

@property (strong, nonatomic) NSString *networkProperty;
@property (strong, nonatomic) NSString <Ignore> *additionalProperty;

@end
```

**Comment by justme1** [comment]
Thanks.
