### ISSUE TITLE
ConvertOnDemand for JSON Array

### ISSUE THREAD

**Issue by aprofromindia** [icanzilb/JSONModel#359]
Is there a way to do ConvertOnDemand NSArray <JSONModel, ConvertOnDemand> * for the following kind of JSON Array response please?

[
    {"id": 1, "name": "jim"},
    {"id": 2, "name": "lovy"}
]

**Comment by billinghamj** [comment]
Not unless it has an outer wrapper for the object. If you want to deserialize an array directly, you can use one of:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
- `+arrayOfModelsFromString:error:`
