### ISSUE TITLE
iOS 9, NSDictionary object call JSONString, result in EXC_BAD_ACCESS code=exc_i386_gpflt

### ISSUE THREAD

**Issue by luna-moonfang** [icanzilb/JSONModel#370]
No problem with xcode 6.4, iOS 8. But Xcode 7 iOS 9 got this issue. Any help?

**Comment by xiaozi4624** [comment]
I have the same problem ，any help?

**Comment by jiangxinxie** [comment]
same problem ，any help?

**Comment by hongruqi** [comment]
me too, help?

**Comment by linfeng** [comment]
me too, help

**Comment by evfemist** [comment]
same for me, anyone know workarounds?

**Comment by captain-zhu** [comment]
me too, help?

**Comment by evfemist** [comment]
In my case - that was issue on my side

**Comment by sauvikatinnofied** [comment]
@captain-zhu @xiaozi4624 @hongruqi will you please provide the JSON string response and object modelling class and object creating code? That will be easier to trace the issue.

**Comment by captain-zhu** [comment]
I found my problem.I used a api, it give me the JSON format is rated = { value = ?}, but when no rated value, it back the format : rated = 0. I set my JSON Model a property NSArray *rated. It caused crash.
So this is my issue.But I wonder if there is way to deal with this JSON. Can I set a NSNumber *rated and NSArray *rated same time?

**Comment by sauvikatinnofied** [comment]
Please add the detailed JSON for different scenarios.

**Comment by billinghamj** [comment]
Is this issue still persisting? If it is, please provide example JSON input & Obj-C model so we can test.

**Comment by luna-moonfang** [comment]
@billinghamj sorry I've changed my job. I am not working on that code any more. So I cannot provide the code example.

Since others had the same issue, maybe someone could provide the example code. Or you can close this post. Thank you for replying.

**Comment by billinghamj** [comment]
Okey dokey, closing for now. Please create a new issue if the issue appears again, along with sample code.
