### ISSUE TITLE
New Objective C syntax (lightweight generics)

### ISSUE THREAD

**Issue by pjebs** [icanzilb/JSONModel#376]
In the new version of Objective C (on XCode 7), we can now specify what a NSArray can contain.

Will your library support this? It will definitely reduce the amount of casting we need to do.

Say we have a JSONModel subclass called Cars.

Say we have another JSONModel subclass called Person:

@property (strong, nonatomic) NSArray < Cars * > * cars; //Restricting NSArray to Cars 

rather than currently:

@protocol Cars
@end

@property (strong, nonatomic) NSArray < Cars >  * cars; //Currently

**Comment by vaddieg** [comment]
W/ Xcode 7 you have to declare protocol name explicitly to suppress compiler error

**Comment by MellongLau** [comment]
Hope @pjebs opinion can be accepted.

**Comment by MellongLau** [comment]
find the answer : [http://stackoverflow.com/questions/30866197/how-can-i-find-out-the-objective-c-generics-type](http://stackoverflow.com/questions/30866197/how-can-i-find-out-the-objective-c-generics-type)

> The lightweight generics introduced in Xcode 7 are just compile time hints to help the compiler raise warnings, but at run time you get the same old behavior with your variable being just NSArrays of ids.

So, I think it is not possible to do some thing like that.

**Comment by KonradZdunczyk** [comment]
Workaround:
```
@interface Model: JSONModel
@property (strong, nonatomic) NSArray < Cars * > * cars;
@end

@implementation Model
- (void)setCars:(NSArray<NSDictionary*> *)cars {
    NSMutableArray* mutArray = [NSMutableArray array];
    
    for (NSDictionary* carDict in cars) {
        NSError* error;
        Cars* car = [[Cars alloc] initWithDictionary:carDict error:&error];
        
        if (car && !error) {
            [mutArray addObject:car];
        }
    }
    
    _cars = [NSArray arrayWithArray:mutArray];
}
@end
```

Unfortunly you need to do this with every array.

**Comment by Johnykutty** [comment]
I also tried this by adding new type annotation(with generics) with arrays, but its not giving any information about the added annotation/generics in runtime. 
That is while fetching property attributes with `property_getAttributes()` its not giving any information about the annotation.

@icanzilb , @dbachrach do you have any thoughts about this?

**Comment by dbachrach** [comment]
Yeah, the objc generics implementation does not persist data at runtime, so it's not usable to JSONModel.

**Comment by skerkewitz** [comment]
Looks to me like it is even worse:

If you do:
```
@protocol Cars
@end
@property (strong, nonatomic) NSArray <Cars> *cars; // JSONModel way
```
then Swift will map cars to [AnyObject] as Swift does not know the type.

If you do:
```
@property (strong, nonatomic) NSArray <Cars *> *cars; 
```
Then swift will map it to [Cars] but JSONModel will not parse the json correctly as it does not know the type. So it seems like you can't have both.

**Comment by pjebs** [comment]
I turns out you can have both. <cars *, cars>

**Comment by MellongLau** [comment]
@pjebs, you can not do that, it will cause compile error.

**Comment by vaddieg** [comment]
Fortunatelly, you can use C macro w/ setCars: workaround
#define JSON_SETTER(className)

**Comment by pjebs** [comment]
@vaddieg can you elaborate  and give more details of usage?

**Comment by vaddieg** [comment]
```obj-c
#import "JSONModel.h"

#define JSONSetterImp(setterSignarure, ClassName, ivarName) \
- (void) setterSignarure :(NSArray<NSDictionary*> *)array {\
    NSMutableArray *ma = [NSMutableArray arrayWithCapacity:array.count];\
    for (NSDictionary* object in array) { \
        ClassName *model = [[ClassName alloc] initWithDictionary:object error:NULL]; \
        if (model) { \
            [ma addObject:model]; \
        } \
    } \
    ivarName = [ma copy];\
}

@interface Car : JSONModel
@end

@interface Parking : JSONModel
@property (strong, nonatomic) NSArray<Car*> *cars;

@end
```

And Implementation of setter will look like:
```obj-c
@implementation Parking

JSONSetterImp(setCars, Car, _cars)

@end
```

**Comment by pjebs** [comment]
I have verified that you can do this:
`<cars *><cars> 
`

**Comment by MellongLau** [comment]
@pjebs GOOD JOB.

**Comment by vaddieg** [comment]
@pjebs Nice. Case is closed I think

**Comment by vaddieg** [comment]
@icanzilb pls update Readme.md Model Collection example
