### ISSUE TITLE
Options for implementation in Swift

### ISSUE THREAD

**Issue by samskiter** [icanzilb/JSONModel#377]
I just thought I'd get down some thoughts I had for JSON deserialization in swift:

1. Reflection (not possible at the current time)
As you say, Swift is different from Obj-C under the hood and it seems to me that we'd need proper reflection in Swift to deserialise dynamically. As I also work on Android apps, I'm quite familiar with using GSON, which is reflection. It wouldn't surprise me if a modern language like Swift arrived at same type of solution. Obviously Swift doesn't have a proper reflection API yet, but obviously that's coming.

2. Code generation
Rather than doing all the lookup at runtime, the information required to create the logic is all available at compile time. Adding a code generation step to create the Swift classes might also result in better performance. I'd note that a project already exists to do the generation (https://github.com/tomlokhorst/swift-json-gen Blog post: http://tomlokhorst.tumblr.com/post/119966903324/json-swift-with-code-generation ) but there's not reason we can't have two :)

Are there any other approaches I'm missing?

**Comment by billinghamj** [comment]
JSONModel is an obj-c library, and it's pretty likely to remain that way. Another JSON modelling library might make sense in Swift, but it'd probably be under a different name. Aren't there many already though?
