### ISSUE TITLE
Deserialising a JSON that contains a field called description

### ISSUE THREAD

**Issue by a1cooke** [icanzilb/JSONModel#382]
This is more of a question than an issue but looking at the examples I don't see an obvious solution.

We have a JSON object response that contains a field called `description`.

By default we have the following in our code:

```
+(JSONKeyMapper*)keyMapper {
    return [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase];
}
```

Is there a way to augment this so that we have have a field called `ticketDescription` which maps to `description` in our JSON while using a global key mapper?

**Comment by sauvikatinnofied** [comment]
Declare the `ticketDescription` as the property name in the `.h` model class file. Implement the following key mapper class method in the `.m` file of your model class. That's it. 

```objective-c
+ (JSONKeyMapper*)keyMapper{
    return [[JSONKeyMapper alloc]initWithDictionary:@{
                                                      @"description":@"ticketDescription"
                                                     }];
    
}
```

**Comment by dabvid** [comment]
I use this on a global level for all my models.

[JSONModel setGlobalKeyMapper:[[JSONKeyMapper alloc] initWithDictionary:@{@"description":@"_description"}]];

**Comment by a1cooke** [comment]
Thanks for clarification, I will try this out today, appreciate the comments, will let you know
