### ISSUE TITLE
How to map unknown keys ?

### ISSUE THREAD

**Issue by frntz** [icanzilb/JSONModel#384]
Hi there,
I'm trying to serialize a JSON object with a "metadata" key containing an object with unknown keys ...

How to do the mapping with the JSONModel ?

Thank you

**Comment by sauvikatinnofied** [comment]
It is not possible, as the keys are unknown to JSONModel. It will be better if you declare that metadata model as NSDictionary then assess all the values using 

```objective-c
for key in [metaDictionary allKeys] {
   NSLog(@"Key: %@: Value: %@", key, metaDictionary[key]);
}
```

**Comment by frntz** [comment]
Thank you so much :) It works perfectly !
