### ISSUE TITLE
Saner NSURL value mapping by default

### ISSUE THREAD

**Issue by technocoreai** [icanzilb/JSONModel#385]
In e798444e6e0b0f2bfe3e479d69ef7d96cedee719, the default NSURL transformer was changed to percent-escaping by default. Not only is it a bad idea in general (see [this document](http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding#CommonpitfallsofURLs) for details), but it also means that if the JSON API you're consuming is sane and emits properly encoded URLs, which is most likely the case for most APIs, the NSURLs you get from the decoded models will be broken, with every `%20` replaced with `%2520` and so on. Please consider disabling the behavior by default, or at least adding a setting to opt out of it.

**Comment by billinghamj** [comment]
You're correct - this should not have happened and conflicts with #119 where I fixed it initially. Need to prevent this from being changed again.

**Comment by billinghamj** [comment]
Corrected in b5f0b466cbf83511b4c104d0f6e0e27812525626 & a75e750a3bdb308347e1629a59a09c477c4289a8. Hopefully will prevent this from happening again.
