### ISSUE TITLE
Retrieve response status code from header in JSONHttpClient.

### ISSUE THREAD

**Issue by dabvid** [icanzilb/JSONModel#386]
Our application needs to act upon different status codes from the http response header.
Can I retrieve the response header from JSONHttpClient somehow or access the status codes?
For example I need to do x when I get status 204 and something else when I get 302, 400 etc.
Thanks!

**Comment by sauvikatinnofied** [comment]
Well you will find a little bit of difficulty while implementing that, you have to modify  `JSONHTTPClient` class files.

Add the following class method in '.h'
```objective-c
+ (NSUInterger) responseStatusCode;
```
Now you can use a static property to have latest response code from server. Declare the following variable in `.m`.
`static NSUInterger responseStatusCode = 0 // Default value`

In. Find out the following code in  `JSONHTTPClient.m` file.
```objective-c
    //if not OK status set the err to a JSONModelError instance
	if (response.statusCode >= 300 || response.statusCode < 200) {
        //create a new error
        if (*err==nil) *err = [JSONModelError errorBadResponse];
    }
```
Put the following log just bellow of those lines
```objective-c
responseStatusCode =  (int)response.statusCode;
```
And define this methods

```objective-c
+ (NSUInterger)current responseStatusCode{
   return responseStatusCode;
}
```

Access the status code from your call back in the following way.
```objective-c
[JSONHTTPClient postJSONFromURLWithString:@"http://mydomain.com/api"
                                   params:@{@"postParam1":@"value1"}
                               completion:^(id json, JSONModelError *err) {

                                   //check err, process json ...
                                   int statusCode =  JSONHTTPClient.responseStatusCode()
                               }];
```

**Comment by dabvid** [comment]
Thanks a lot! Very helpful. Would you mind doing a merge request of the suggested implementation? Or mind if I do?

**Comment by sauvikatinnofied** [comment]
Please go ahead.

**Comment by billinghamj** [comment]
To be honest, you'd probably be better using a more capable & generic request library, like NSURLSession, AFNetworking, etc.

JSONHTTPClient is only really intended for basic use cases.

**Comment by dabvid** [comment]
Thanks, I ended up solving this by doing a workaround with NSURLSession.
