### ISSUE TITLE
Direct conversion of NSError to JSONString?

### ISSUE THREAD

**Issue by kylemiller3** [icanzilb/JSONModel#391]
Is there any way to do this? Currently I have a JSONValueTransformer+NSError category and a custom object holding my error.

In order to log the error in JSON I have to do this:
NSLog(@"%@", [[Model alloc] initwithError:error].toJSONString);

I would prefer to do this:
NSLog(@"%@", error.toJSONString);

anyway to do this or should I just make a macro and be done with it?

**Comment by billinghamj** [comment]
The way you're doing it seems probably the best way. NSErrors can be rather complex objects and do not have serialization methods.
