### ISSUE TITLE
Keep some property with raw data

### ISSUE THREAD

**Issue by TheWalkingDead1024** [icanzilb/JSONModel#396]
Hi，I have got a data convert problem.The following is my model data structure.

@interface SystemNotificationModel : BaseModel
@property (nonatomic, strong) NSDictionary* message;

@property (nonatomic, strong) NSString *created_at;

@property (nonatomic, strong) NSString *message_id;

@property (nonatomic, strong) NSString* msg_type;

@property (nonatomic, strong) NSString* content;

- (NSString*)getCreateTime;
@end

The property message is a NSDictionary Class.I have read your instruction. If I use collection properties like NSArray, NSDictionary, the property should conform some protocol whose name is the same with the real Class name. But I just want to keep the raw data，I means do not conform any protocols, just keep the property "message" with original data, do not transfer it to any models. I do not think it is going work, then crash.Could Anybody can help me with this problem?Many thanks.

**Comment by sauvikatinnofied** [comment]
Will you please show us the original string data coming from server?

**Comment by TheWalkingDead1024** [comment]
@sauvikatinnofied ,thanks for your reply, data coming from server is in varied forms, so I just want to keep it a dictionary.For example, message = {"avatar":http://123456, "nickname":"the walking dead"}, or message could be {"identifier":5211314, "sex":"male", "salary":"19k"}, and so on. I do not know If you understand what I said.My English is not good. Thank you again.

**Comment by sauvikatinnofied** [comment]
If you are getting JSON string for message in that following way
```json
    "message": {
        "avatar": "http://123456",
        "nickname": "the walking dead"
    }
```
, then you have done modelling correctly. Will you please confirm the line of code
``` objective-c
@interface SystemNotificationModel : BaseModel
```
is actually 
``` objective-c
@interface SystemNotificationModel : JSONModel
```
?

**Comment by TheWalkingDead1024** [comment]
Thanks for your reply.I confirm is actually @interface SystemNotificationModel : JSONModel. Base Model Inherit from JsonModel. Thanks again.

**Comment by sauvikatinnofied** [comment]
You are most welcome. Please let me know whether your model class is working fine or not.

**Comment by TheWalkingDead1024** [comment]
Thank you. My model class is not working fine. I change message property from  nsdictionary to nsstring.I transfer dictionary to string to store value, or it will crash. I thought the crash reason is that my model class "message" property did not confirm any protocol, so JSONModel can not find any Model to transfer.

**Comment by TheWalkingDead1024** [comment]
@sauvikatinnofied ,hi, are you there?Could you help me with my problems above-mentioned.Many thanks.

**Comment by TheWalkingDead1024** [comment]
@sauvikatinnofied ,I am so sorry. My friend who use the version 0.13.0 said that JSONModel support for keeping dictionary property with raw data already.It is my fault.So stupid.\(^o^)/~.Thank you for your time.
