### ISSUE TITLE
JSON Serialization

### ISSUE THREAD

**Issue by classified** [icanzilb/JSONModel#397]
Hello, i want to serialize json from my model but i am unable to do it.

JSON Format :
``````
[
  {
    "restaurantId": 2494,
    "typeObject": [
      {
          model 1
      },{
          model 2
      },{
          model 3
     }
 }
]


can i achieve this?

**Comment by sauvikatinnofied** [comment]
You can create a new dictionary with the following syntax
```json
"yourKey" : [
  {
    "restaurantId": 2494,
    "typeObject": [
      {
          model 1
      },{
          model 2
      },{
          model 3
     }
 }
]
```
Use this dictionary to create your model class.

**Comment by billinghamj** [comment]
You can do the first option actually.

Use one of the following methods:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
