### ISSUE TITLE
Map initial JSON array containing model objects to an NSArray of model objects

### ISSUE THREAD

**Issue by mikeCalvir** [icanzilb/JSONModel#401]
Hi,
All the examples show JSONModel objects initialised directly from a string with a JSON dictionary.
Sorry for being slow, but I'm not seeing how to initialise from a string containing an array, of the form:
[ { something = somethingElse, etc }, { another = anotherThing, etc }, .... ]

Any pointers?

Many thanks!

**Comment by sauvikatinnofied** [comment]
Will you please check https://github.com/icanzilb/JSONModel/issues/397?

**Comment by mikeCalvir** [comment]
Thanks Sauvik.
I haven't exactly tried that yet. 
I have tried passing NSDictionaries (received from AFNetworking) into the method: arrayOfModelsFromDictionaries
However I am not sure if that is expecting Dictionaries in the ObjC sense, but instead is expecting NSString objects containing JSON format content in each object. I suspect the latter.

What I was hoping for really was something like this on JSONModel:
+ (NSArray *)arrayOfModelsFromJSON:(NSString *)stringOfJSONArray;

When you suggest that I change the text to:

"someKey" = <incoming array>

And then presumably I make some kind of Holder object to map that to it, and then finally extract the array I want from that. 

This seems to be something quite blatantly missing from this library then?

**Comment by mikeCalvir** [comment]
Ok that worked, I create a placeholder object like you suggest, and then called arrayOfModelsFromDictionaries on my model passing in the array property of the holder, and that gets the mapping going. 
Thanks Sauvik :)

(I still think this is something surprising to be missing though, mapping a root array response from a web service is the most common mapping I ever see).

**Comment by sauvikatinnofied** [comment]
That's great. :smile: Actually I also faced same problem while getting an array from server instead of a dictionary. I tried to use that array to make a dictionary and then using the dictionary format, I used to model my JSONModel subclasses.

**Comment by billinghamj** [comment]
@mikeCalvir Equivalents to that method do exist btw:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`

**Comment by mikeCalvir** [comment]
@billinghamj thanks yeah, look at my question and comments though. I am using that but I have to create my own "holder" first. Unless I am missing something simpler :)

My point is that for a dictionary it is fully automatic and I can just get back the model immediately, for an array however I have to put something in-between to get the model straight away. It doesn't matter much it was just surprising (and I still suspect I am am missing something v simple).

So for example in my network response block is code like this (stripped to illustrate):

      NSString *holderString = [NSString stringWithFormat:@"{\"array\":%@}", thisOp.responseString];
      MLArrayHolder *holder = [[MLArrayHolder alloc] initWithString:holderString error:NULL];

And then I access the array via holder.array.
IIRC I tried passing in the data to arrayOfModelsFromData but it failed. Maybe I gave up too easily.

**Comment by billinghamj** [comment]
@mikeCalvir I don't think you need to do that. This code would work fine too:

```objc
NSData *data = [thisOp.responseString dataUsingEncoding:NSUTF8StringEncoding];
NSArray *array = [MyModel arrayOfModelsFromData:data error:nil];
```

`array` will then be an array of type `MyModel`. Perhaps we could add a `FromString` version also though.

**Comment by mikeCalvir** [comment]
Thanks I'll try that next time I'm back to that project. 
Yeah maybe it could be made slightly more obvious for people like me :)

**Comment by sauvikatinnofied** [comment]
Thanks @billinghamj  for specifying those important modelling mechanism while there is a simple list of dictionaries coming from server as JSON data.

**Comment by billinghamj** [comment]
No problem. I've also just added another method which makes it a one-liner:

```objc
NSArray *array = [MyModel arrayOfModelsFromString:thisOp.responseString error:nil];
```

**Comment by mikeCalvir** [comment]
Nice, that's the one I was looking for ;)
