### ISSUE TITLE
Converting jsonarray (having different type) to model array using JSONModel Library

### ISSUE THREAD

**Issue by alok-rao** [icanzilb/JSONModel#404]
I have one problem in converting JSON array to model. I am using JSONModel library.

@protocol PTTemplateModel <NSObject>

@end

@protocol PTProfileTemplateModel <PTTemplateModel>

@end

@protocol PTCategoryTemplateModel <PTTemplateModel>

@end

    @interface PTTemplateModel : JSONModel
    @property (nonatomic, assign) TemplateType type;
    @property (nonatomic, copy) NSString* templateID; 
    @end

    @interface PTProfileTemplateModel : PTTemplateModel
    @property (nonatomic, copy) NSString* logoURL;
    @property (nonatomic, copy) NSString* title;
    @end

    @interface PTCategoryTemplateModel : PTTemplateModel
    @property (nonatomic, strong) NSString* category;
    @end

    @interface PTModel : JSONModel
    @property (nonatomic, copy) NSString* title;
    @property (nonatomic, strong) NSArray< PTTemplateModel>* templates; // PTTemplateModel
Here templates array can have both PTProfileTemplateModel and PTCategoryTemplateModel.

JSON Input:

{"title":"Core","templates":[{"type":0,"templateID":"","logoURL":"", "title":"data"},{"type":1,"templateID":"","category":"DB"}]}
What I need is according to type I have to get CategoryTemplate or ProfileTemplate. But after conversion I am getting just PTTemplateModel type.

I know that I have specified protocol type as PTTemplateModel. But how do I get different type of model according to given data.

I tried:

@property (nonatomic, strong) NSArray< PTTemplateModel>* templates;

@property (nonatomic, strong) NSArray<PTProfileTemplateModel, PTCategoryTemplateModel>* templates;

@property (nonatomic, strong) NSArray< PTTemplateModel , PTProfileTemplateModel, PTCategoryTemplateModel>* templates;

None of them works.

Any suggestions?

**Comment by poledeveloper** [comment]
I have the same problem!
It's a perfect library, help me please! :)
Thanks

**Comment by sauvikatinnofied** [comment]
It might be an issue with J`SONModel` library. It will not help you if you are trying to keep multiple type of objects in an `NSArray`of JSONModel subclass specifying multiple protocol type, I suppose.

Anyway I fixed the issue using some manual tasks by overriding and manual parsing in `initWithDictionary:error:` method of `PTModel` class.

Here is my code

**Interface File**
`PTModel.h`

```objective-c
#import "JSONModel.h"

@interface PTModel : JSONModel

@property (nonatomic, copy) NSString *title;
@property (nonatomic, strong) NSArray *templates; // Simple Template
@property (nonatomic, strong) NSArray<Optional> *modelTemplates; // PTTemplateModel

@end

```

**Implementation File**
`PTModel.m`


```objective-c
#import "PTModel.h"
#import "PTProfileTemplateModel.h"
#import "PTCategoryTemplateModel.h"

@implementation PTModel

- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError *__autoreleasing *)err{
    
    if (self = [super initWithDictionary:dict error:err]) {
        
        
        // Custom initialisation code goes here
        
        if (_templates.count > 0) {
            
            // Allocation for memory to keep custom template model objects
            NSMutableArray *templateArray = [[NSMutableArray alloc]init];
            
            for (NSDictionary *templateDictionary in _templates) {
                                
                switch ([templateDictionary[@"type"] integerValue]) {
                        
                    case 0: {
                        
                        // Found PTProfileTemplateModel
                        NSError *jsonParsingError;
                        PTProfileTemplateModel *model = [[PTProfileTemplateModel alloc]initWithDictionary:templateDictionary error:&jsonParsingError];
                        if (!jsonParsingError) {
                            [templateArray addObject:model];
                        } else {
                            NSLog(@"PTProfileTemplateModel JSON Parsing Error = %@", jsonParsingError.localizedDescription);
                        }
                        
                    }
                        break;
                        
                    case 1: {
                        
                        // Found PTCategoryTemplateModel
                        NSError *jsonParsingError;
                        PTCategoryTemplateModel *model = [[PTCategoryTemplateModel alloc]initWithDictionary:templateDictionary error:&jsonParsingError];
                        if (!jsonParsingError) {
                            [templateArray addObject:model];
                        } else {
                            NSLog(@"PTCategoryTemplateModel JSON Parsing Error = %@", jsonParsingError.localizedDescription);
                        }
                    }
                        
                        break;
                        
                    default:
                        break;
                }
            }
            self.modelTemplates = [templateArray copy];
        }
        
    }
    
    return self;
}
@end
```

Let me know it it's working or not.

**Comment by billinghamj** [comment]
This is effectively a classic case for class clustering. You should override the `initWithDictionary:` method of `PTTemplateModel`. This is how I have implemented the same thing before: https://github.com/icanzilb/JSONModel/issues/229#issuecomment-52556421
