### ISSUE TITLE
type convert

### ISSUE THREAD

**Issue by HuiiChung** [icanzilb/JSONModel#405]
I have a property like this:
@property (nonatomic, strong) NSArray<Optional> *thumb;
if server return the property like this:
{
thumb="";
}
then,the app is crashed.I think it can return an error not crashed. for this,Jsonmodel is strong.
Do you think so?

**Comment by sauvikatinnofied** [comment]
Make sure that the server always sends `thumb` as an array. Here in sample response 
```json
{
thumb="";
}
``` 
thumb is just the `NSString`. That's why you are getting the crash.

**Comment by HuiiChung** [comment]
Sorry, I don't describe clearly.This question is:
when the server return correct, the [thumb] is an array, like this:
{
thumb=("aaa","bbb");
}
but, if the array is empty, it will return:
{
thumb="";
}
I know, I can tell the server to modify the field.but server maybe change,
so,I wanna, in this case , It's not crashed.

**Comment by billinghamj** [comment]
You can handle this by having custom setters:

```objc
- (void)setThumbWithNSArray:(NSArray *)array
{
  _thumb = array;
}

- (void)setThumbWithNSString:(NSString *)string
{
  if (string.length == 0)
    _thumb = nil;

  // undefined behavior
}
```
