### ISSUE TITLE
JSONValueTransformer do not work for array of custom object

### ISSUE THREAD

**Issue by jokefaker** [icanzilb/JSONModel#406]
I have two JSONValueTransformer methods named:
- (SOMedia *)SOMediaFromNSString:(NSString*)string;// SOMedia is a subclass of NSObject
- (id)JSONObjectFromSOMedia:(SOMedia *)media;

Now I have a class Building which has a property like 
* NSArray<SOMedia> *medias;// It is still an array of NSString
* SOMedia *media;// It works well

Is it possible to let it convert array of NSString to array of SOMedia?

**Comment by aprofromindia** [comment]
facing the same problem trying to get JSONString from an array of custom objects. Getting NSInvalidArgumentException error.

**Comment by billinghamj** [comment]
@aprofromindia JSONModel cannot be used to serialize arbitrary Obj-C objects. This is not likely to change.
