### ISSUE TITLE
Cant create <Optional, CustomModel> ... 

### ISSUE THREAD

**Issue by murilonkz** [icanzilb/JSONModel#410]
Hello Everyone, 

I'm with a problem here... I created a object like the documentation of JSONModel, but xcode show me a error on property... 

![captura de tela 2015-12-10 as 00 59 41](https://cloud.githubusercontent.com/assets/5704892/11705716/506f6648-9ed9-11e5-8085-19754bdeaf76.png)

Anyone can help-me?

**Comment by billinghamj** [comment]
You need to define the `Player` protocol (in addition to the class).

E.g.:

```objc
@protocol Player;
```
