### ISSUE TITLE
Type not supported exception for dictionary fields

### ISSUE THREAD

**Issue by burakkilic** [icanzilb/JSONModel#411]
Hello;

My Entity model is something like

    @property (nonatomic, strong) NSString *name;
    @property (nonatomic, strong) NSString *description;

In the .m file, I wrote that methods:

    - (void)setNameWithNSDictionary:(NSDictionary*)dictionary {
    self.name = [dictionary valueForKey:[Helper currentLanguageCode]];
    if([self.name isEqual:[NSNull null]]){
        self.name = @"";
    }
    }
    - (void)setDescriptionWithNSDictionary:(NSDictionary*)dictionary {
    self.description = [dictionary valueForKey:[Helper currentLanguageCode]];
    if([self.description isEqual:[NSNull null]]){
        self.description = @"";
    }
    }

If I first run the app, there is no exception. But if I re-call the method, it throws an exception with the same data. 

     Terminating app due to uncaught exception 'Type not allowed', reason: 'NSString type not supported for Shop.description'

Dictionary that loaded is https://gist.github.com/burakkilic/46d3acd20d3482609994

Where am I wrong?

UPDATE: I check the working and non-working datas in an online diff checker tool. The 2 data are identical. 

The difference between the operations is, in the working function, I delete the app and get the data from an api.

In not working example, I call the same function to retrieve data from the api. This time I see that error with the same data. Really strange!

**Comment by billinghamj** [comment]
This may relate to a recently-fixed issue where you could not have setters for multiple different types. That was resolved by #412.

Could you try using that code (not released to Cocoapods yet) and see if your issue still persists?

**Comment by burakkilic** [comment]
Thank you @billinghamj . I downloaded the library, not from Cocoapods, and it is working now. How Cocoapods library will be updated soon.

**Comment by billinghamj** [comment]
@burakkilic Excellent - I'm glad the new changes resolve your issue.

I am hoping that we'll be able to make a release to Cocoapods soon. I just need to arrange it with @icanzilb.
