### ISSUE TITLE
Demo app fails on Xcode 7.2 / ios 9.2

### ISSUE THREAD

**Issue by icanzilb** [icanzilb/JSONModel#414]
iOS App
* kiva demo fails bcz it makes a call to non https url
* youtube demo crashes (maybe json structure change?)

OSX app will have similar issues, I'll check that

**Comment by icanzilb** [comment]
I'll take care to update the apps

**Comment by icanzilb** [comment]
fixed kiva api calls, removed youtube demo because they closed off the free API access

**Comment by billinghamj** [comment]
:+1:
