### ISSUE TITLE
How to remove a NSArray object using JSONModel

### ISSUE THREAD

**Issue by zhengjin** [icanzilb/JSONModel#415]
"loans": [{
    "id": 547665,
    "name": "Veronica",
    "description": {
        "languages": ["en", "cn", "ja"]
    },
    "status": "fundraising",
    "funded_amount": 0,
}]
Lazy convert collection items from dictionaries to models
@interface KivaFeed : JSONModel
@property (strong, nonatomic) NSArray<LoanModel, ConvertOnDemand>* loans;
@property (strong, nonatomic) Paging *paging;
@end

I want to remove the "loans", 
but  IDE warning "No visible @interface for 'NSArray< loans,ConvertOnDemand >' declares the selector 'removeAllObjects'"

**Comment by billinghamj** [comment]
@zhengjin This is because the NSArray is not mutable. Instead, you could do:

```objc
feed.loans = [NSArray new];
```
