### ISSUE TITLE
how to write a keymapper ?

### ISSUE THREAD

**Issue by TuWei1992** [icanzilb/JSONModel#420]
```Objective-c
@interface User : BaseModel

@property (nonatomic, strong) NSString *id;
// loginname
@property (nonatomic, strong) NSString *loginName;
// avatar_url
@property (nonatomic, strong) NSString *avatarUrl;
@property (nonatomic, strong) NSString *githubUsername;
// create_at
@property (nonatomic, strong) NSDate   *createAt;
@property (nonatomic, assign) int      score;
// recent_topics : Topic
@property (nonatomic, strong) NSArray  *recentTopics;
// recent_replies : Topic
@property (nonatomic, strong) NSArray  *recentReplies;

@end
```
```
{ 
"loginname":"wendal",
"avatar_url":"https://nutz.cn/yvr/u/wendal/avatar",
"recent_topics":[], 
...
}
```

I want to use mapperFromUnderscoreCaseToCamelCase, but in the JSON "loginname" does not use the camel naming specifications, how I should extend the keymapper, I don't want to write all the attributes in dic

**Comment by jiyee** [comment]
see 

/* 
* based on a built-in JSONKeyMapper, with specific exceptions.
 * Use the original JSON key names as keys, and your JSONModel property names as values.
 */
+ (instancetype)mapper:(JSONKeyMapper *)baseKeyMapper withExceptions:(NSDictionary *)exceptions;

**Comment by icanzilb** [comment]
:100:
