### ISSUE TITLE
Deserializing a 'root' JSON object with an arbitrary number of keys

### ISSUE THREAD

**Issue by benjibobs** [icanzilb/JSONModel#421]
Hello, I cannot figure this out for the life of me, so I thought I would post it here to see if I am missing anything stupid.

I am looking for a way to allow my JSONModel to pick up all entries in a json string arranged such as 

```{"1":{"name":"josh"},"2":{"name":"susan"}}``` etc

Is it possible? The numbers would go up in the thousands.

**Comment by benjibobs** [comment]
Implemented my own method

**Comment by billinghamj** [comment]
JSONModel does support deserializing into an `NSDictionary` with arbitrary `NSString` keys, and a set of JSONModel subclass instances. However, currently it only supports doing this to a property within a larger object. We could probably expose a special method which allows you to do this with a 'root' JSON object.

Could you also share the method you implemented yourself?

@icanzilb Any thoughts on this? I'm thinking that implementing methods like this would be useful:

- `+dictionaryOfModelsFromDictionaries:error:`
- `+dictionaryOfModelsFromData:error:`
- `+dictionaryOfModelsFromString:error:`

Equivalent to these existing methods for arrays:

- `+arrayOfModelsFromDictionaries:error:`
- `+arrayOfModelsFromData:error:`
- `+arrayOfModelsFromString:error:`

This would allow you to deserialize a JSON object with an arbitrary set of keys.

**Comment by benjibobs** [comment]
```Objective-C
[JSONHTTPClient getJSONFromURLWithString:@"jsonaddress"
                                  completion:^(NSDictionary *json, JSONModelError *err) {
                                      
                                      //You can now iterate through the dictionary without having to specify the key "1","2" etc

}

**Comment by benjibobs** [comment]
It may not be the best way to go about it, but it works.

**Comment by billinghamj** [comment]
@benjibobs You can achieve this more cleanly now with https://github.com/icanzilb/JSONModel/commit/0e9d509926d30c939a4ec792c1f30a2d7101f3e0:

```objc
[JSONHTTPClient getJSONFromURLWithString:@"https://example.com" completion:^(NSDictionary *json, JSONModelError *err) {
  NSError *error;
  NSDictionary *dict = [MyModel dictionaryOfModelsFromDictionary:json error:&error];
}];
```

Then, `dict[@"1"]` will be an instance of `MyModel`.
