### ISSUE TITLE
BOOLFromNSString in JSONValueTransformer not called

### ISSUE THREAD

**Issue by jiyee** [icanzilb/JSONModel#423]
Because if property type is primitive, it will call generic setter method, not call customSetterMethod. and UnitTest not cover this.

**Comment by billinghamj** [comment]
@jiyee As per [the issue rules](Repo.md), please provide:

0. Describe what you expected to happen
0. What actually happened instead?
0. The JSON relevant to the problem
0. Your Objective-C model code
