### ISSUE TITLE
How to convert NSArray to JSON string

### ISSUE THREAD

**Issue by zhengjin** [icanzilb/JSONModel#425]
@protocol ProductModel
@end

@interface ProductModel : JSONModel
@property (assign, nonatomic) int id;
@property (strong, nonatomic) NSString* name;
@property (assign, nonatomic) float price;
@end

@implementation ProductModel
@end

@interface OrderModel : JSONModel
@property (assign, nonatomic) int order_id;
@property (assign, nonatomic) float total_price;
@property (strong, nonatomic) NSArray<  ProductModel  >* products;
@end

@implementation OrderModel
@end

I want to convert from NSArray to json string.
For example:
[products toJSONString],but IDE warning 'No visible @interface for 'NSArray< ProductModel >' declares the selector 'toJSONString'

**Comment by billinghamj** [comment]
```objc
[ProductModel arrayOfDictionariesFromModels:array];
```

**Comment by neobie** [comment]
I get the error : Invalid type in JSON write (JSONClass)
with [NSJSONSerialization dataWithJSONObject]. Why is that happening?
