### ISSUE TITLE
Properties with unsupported types marked with Ignore cause the parsing to fail.

### ISSUE THREAD

**Issue by J-Rojas** [icanzilb/JSONModel#431]
Here's a sample:

    @interface GenericObjectModel : JSONModel
    @property (nonatomic, strong) NSString<Optional>* id;
    @property (nonatomic, strong) NSString<Optional>* name;
    @property (nonatomic, strong) NSString<Optional>* type;
    @property (nonatomic, strong) Class<Ignore> classType;
    @end

I would expect the classType to be ignored by JSONModel since it is marked with Ignore. However, instead the parsing fails because of the unsupported type.

The ignore should have precedence over the unsupported type check so complex models can be used in a compatible way.

Sample:
    {
      "name": "Joystick",
      "id": "joystick_signaler",
      "_class": "SomeClass"
    }

**Comment by billinghamj** [comment]
Thanks - this does look like a bug. Will investigate at some point.

**Comment by icanzilb** [comment]
yes, that makes sense. @billinghamj I'll have a look

**Comment by icanzilb** [comment]
@J-Rojas making primitive types and structs *Optional* or *Ignored* must be done by overriding `+(BOOL)propertyIsIgnored:(NSString *)propertyName` and `...propertyIsOptional...` Protocols can be used only on class properties with JSONModel. The runtime strips out the protocols defined on a struct so we can't even get this information.

**Comment by icanzilb** [comment]
@J-Rojas re: precedence - if you use *Ignored* with a class property (let's say a `UIImage`) the code works fine
