### ISSUE TITLE
about dictionary value is array

### ISSUE THREAD

**Issue by a0000** [icanzilb/JSONModel#432]
@billinghamj i need help, thanks

```javascript

{
    "response": {
		"49": {
			"count": 6,
			"list": {
				"16:50-17:50": [
					{
						"first_address": "B",
						"order_id": "458260",
						"order_num": 10,
						"time": "16:50-17:50",
						"user_id": "71851"
					},
					{
						"first_address": "B",
						"order_id": "458261",
						"order_num": 11,
						"time": "16:50-17:50",
						"user_id": "71851"
					},
					{
						"first_address": "B",
						"order_id": "458262",
						"order_num": 12,
						"time": "16:50-17:50",
						"user_id": "71851"
					}
				],
				"18:10-19:00": [
					{
						"first_address": "B",
						"order_id": "458263",
						"order_num": 13,
						"time": "18:10-19:00",
						"user_id": "71851"
					},
					{
						"first_address": "B",
						"order_id": "458264",
						"order_num": 14,
						"time": "18:10-19:00",
						"user_id": "71851"
					},
					{
						"first_address": "B",
						"order_id": "458265",
						"order_num": 15,
						"time": "18:10-19:00",
						"user_id": "71851"
					}
				]
			},
			"name": "food"
		}
	},
	"responseTime": "1453710085",
	"result": "true",
	"resultElapse": 6,
	"resultMessage": "success",
	"resultNum": "200"
}

```

```javascript

@interface Response : JSONModel
@property (assign, nonatomic)BOOL result;
@property (assign, nonatomic)NSInteger resultNum;
@property (assign, nonatomic)NSInteger responseTime;
@property (strong, nonatomic)NSString *resultMessage;
@property (strong, nonatomic)NSDictionary <GroupOrder> *response;
@end


@protocol GroupOrder
@end
@interface GroupOrder : JSONModel
@property (strong, nonatomic) NSDictionary<NSString*, NSArray<Order>*> *list;
@property (strong, nonatomic) NSString *name;
@property (nonatomic) int count;

@end

@protocol Order
@end

@interface Order : JSONModel
@property (strong, nonatomic) NSString *first_address;
@property (nonatomic) int order_id;
@property (nonatomic) int order_num;
@property (strong, nonatomic) NSString *time;
@property (nonatomic) int *user_id;

@end
```

how should I declare GroupOrder property list?

**Comment by billinghamj** [comment]
Either:

```objc
@property (strong, nonatomic) NSDictionary <Order> *list;
```

Or if you want to keep the Obj-C generics syntax:

```objc
@property (strong, nonatomic) NSDictionary <NSString *, NSArray <Order *>*> <Order> *list;
```

**Comment by cbornet** [comment]
@billinghamj When I try the syntax
```objc
@property (strong, nonatomic) NSDictionary <NSString *, NSArray <Order *>*> <Order> *list;
```
I get a NSDictionary<NSString *, Order *> as type for list instead of the dictionary of arrays. It's as though the generic is ignored.
Also, I'm not sure how the syntax without generic can map to a dictionary of arrays and not a plain dictionary of orders. Can you help on this ?

**Comment by billinghamj** [comment]
Uh, yeah, JSONModel can't do that.

If you do:

```objc
@property (strong, nonatomic) NSDictionary <Order> *list;
```

It considers the type to be `NSDictionary <NSString *, Order *> *`.

As far as my knowledge goes, there is no way to tell JSONModel that the value type is `NSArray <Order *> *` via the standard protocol directives. Nor does it support other similar type nesting.

I can also pretty positively say that this will not be added as a feature.

Best way to handle this would be using custom setters imo.

**Comment by billinghamj** [comment]
Also I realize I have somewhat contradicted my suggestions above. I guess I slightly missed some of the details of the JSON object.

**Comment by billinghamj** [comment]
Also the generic part **is** ignored. It is a compile-time check only and cannot be accessed by JSONModel because it does not exist in the runtime.

**Comment by cbornet** [comment]
Thanks for your response. I understand that there is no way to have more than one level of dictionary/array in the model. This is bad news as it is precisely what the API I use (not mine, so I cannot change it) does...

**Comment by billinghamj** [comment]
You can still work with the API - just add a custom setter for the relevant properties which handle the exceptional cases.

**Comment by cbornet** [comment]
You mean using [this](https://github.com/icanzilb/JSONModel#custom-handling-for-specific-properties) ? Sounds interesting ! Would you give some hint on how to go next ? I'm not too familiar with the API. For instance for the model above, I guess it would look like:
```obj
- (void)setListWithNSString:(NSString*)string {
    self.list= ...
}

- (NSString *)JSONObjectForList {
    return ...
}
```
But then how do you parse a NSDictionary<NSString *, NSArray <Order *>*> from a string manually. Using dictionaryOfModelsFromString/arrayOfModelsFromDictionaries ?

**Comment by billinghamj** [comment]
Yes indeed. However, it would be `setListWithNSDictionary` - as the whole object is already deserialized into standard Obj-C types.

You'd then do something along these lines:

```objc
- (void)setListWithNSDictionary:(NSDictionary <NSString *, NSArray <NSDictionary *> *> *)dict
{
  NSMutableDictionary *mutableDict = [NSMutableDictionary new];

  for (NSString *key in dict.keys)
    mutableDict[key] = [MyModel arrayOfModelsFromDictionaries:dict[key] error:nil];

  _list = mutableDict;
}
```

Bear in mind, this doesn't currently handle errors and could crash in some circumstances. (`arrayOfModelsFromDictionaries:error:` returns nil on failure)

Also I suspect you probably wouldn't need to implement `JSONObjectForList` - I think that would probably just work.

**Comment by cbornet** [comment]
Thanks, I will try that. I guess "MyModel" is "Order" here ?

**Comment by billinghamj** [comment]
Yup.

**Comment by cbornet** [comment]
Works perfectly ! Thanks for your help !

**Comment by billinghamj** [comment]
No problem :)

**Comment by cbornet** [comment]
@billinghamj sorry to bother you again. Do you think an intermediate class such as 
```objc
@protocol OrderArray
@end

@interface OrderArray: JSONModel
@end

@implementation OrderArray
-(instancetype)initWithDictionary:(NSDictionary*)dict error:(NSError**)err {
    NSMutableDictionary *mutableDict = [NSMutableDictionary new];
    mutableDict = [Order dictionaryOfModelsFromDictionary:dict error:err];
    return [super initWithDictionary:mutableDict error:err];
}

@end
```
could work ?
It would be even better for my use case.

**Comment by cbornet** [comment]
@billinghamj sorry to bother you again. Do you think an intermediate class such as 
```objc
@protocol OrderMap
@end

@interface OrderMap: JSONModel
@end

@implementation OrderMap
-(instancetype)initWithDictionary:(NSDictionary*)dict error:(NSError**)err {
    NSMutableDictionary *mutableDict = [NSMutableDictionary new];
    mutableDict = [Order dictionaryOfModelsFromDictionary:dict error:err];
    return [super initWithDictionary:mutableDict error:err];
}

@end
```
could work if we wanted to map a dictionary of Order ?
It would be even better for my use case. If it's OK, could the same be done with an array of Order ?

**Comment by billinghamj** [comment]
You could, but that definitely falls outside of what JSONModel supports.

**Comment by cbornet** [comment]
Actually, that doesn't work :unamused: . I guess because OrderMap doesn't have the properties that are in the dict.
