### ISSUE TITLE
carthage install does not create Mac framework

### ISSUE THREAD

**Issue by boscomonkey** [icanzilb/JSONModel#433]
While developing for Mac OSX, when I add the appropriate line to my Cartfile and run `carthage install`, the Mac version of the framework is not generated.

In other word, I don't see Carthage/Build/Mac/JSONModel.framework

FWIW, Carthage/Build/iOS/JSONModel.framework is generated properly

**Comment by billinghamj** [comment]
Unfortunately none of the maintainers have much knowledge of Carthage (as far as I know, anyway). It was set up by @cybertk. Do either of you know what is configured incorrectly?

**Comment by cybertk** [comment]
I was only testing it on iOS. I will have a try on Mac.

**Comment by billinghamj** [comment]
Thanks :)
