### ISSUE TITLE
ObjectiveC: "Optional" is not considered when deserialising a typed NSArray

### ISSUE THREAD

**Issue by sureal** [icanzilb/JSONModel#435]
Hi,

I found the following issue:

I have a JSONModel subclass like:
```
@interface Device : JSONModel

@property (nonatomic, strong) Program<Optional> *selectedProgram;
@property (nonatomic, strong) NSArray<Optional, Program *> *availablePrograms;

@end

//and
@interface Program : JSONModel
...
@end
```

The code compiles fine with Xcode 7 for iOS

When I receive a JSON Object without a key "selectedProgram" everything is fine due to the <Optional>  protocol / annotation 

When I receive a JSON Object without a key "availablePrograms" the deserialisation fails because of the missing key.

Hence it seems that Optional is Ignored on collection types.

Did I miss something about optional and typed arrays? I didn't found something in the documentation.

ciao Matthias

**Comment by sureal** [comment]
I need to apologise, it was my mistake:

I missed the lines:

```
@protocol ProductModel
@end
```
and
Note: the angle brackets after NSArray contain a protocol. This is not the same as the new Objective-C generics system. They are not mutually exclusive, but for JSONModel to work, the protocol must be in place.

from documentation. Could you please highlight this even more? I guess with upcoming use of new generic system more devs will run into the same dump problem.

Btw.: is this only needed to keep backwards compatibility? in JSONModels initWithDictionary: one could add also a check for generic types instead on only checking for protocols.

ciao Matthias

**Comment by billinghamj** [comment]
This line exactly:

```objc
@property (nonatomic, strong) NSArray<Optional, Program *> *availablePrograms;
```

Should not be possible. It would have to be as follows:

```objc
@property (nonatomic, strong) NSArray <Program *> <Optional> *availablePrograms;
```

Because you cannot mix generics and protocols within the same angle brackets. I suspect this is how your code should look though:

```objc
@property (nonatomic, strong) NSArray <Program *> <Optional, Program> *availablePrograms;
```

**Comment by sureal** [comment]
Hi

indeed @property (nonatomic, strong) NSArray<Optional, Program *> *availablePrograms;

did compile, but
@property (nonatomic, strong) NSArray<Program *, Optional> *availablePrograms;
did not.

I'm now using this:
@property (nonatomic, strong) NSArray <Program *> <Optional, Program> *availablePrograms;

as suggested which is working fine.

It's a pity that it is required to make each JSONModel subclass collection capable by adding a empty protocol but at least it's working. A solution working with the generic type of the collection could work in ObjC and swift, but I need to dive deeper into this soon.

thanks, I close this ticket.

ciao Matthias

**Comment by utkalpatel** [comment]
@billinghamj Thanks I would request you to please update jsonmodel   ReadMe file with this  code @property (nonatomic, strong) NSArray<Program *, Optional> *availablePrograms; 

I m having same issue and search a lot for making my property optional having protocol.finally got the answer.so thanks

**Comment by billinghamj** [comment]
The code you have there is not correct @utkalpatel. You can't have protocols and classes in the same angle brackets. I believe the README already covers this.

**Comment by billinghamj** [comment]
Ah yes I decided not to include an example of the Obj-C generics because it overcomplicates things and people using the generics should already know the rules & semantics of how they interact with protocols.
