### ISSUE TITLE
toDictionaryWithKeys hard codes importing to YES, seems like it should be NO

### ISSUE THREAD

**Issue by EliSchleifer** [icanzilb/JSONModel#438]
From my reading of the code if using a keymapper it would make sense to me that importing:YES would be written as importing:NO on this line:

        NSString* keyPath = (self.__keyMapper||globalKeyMapper) ? [self __mapString:p.name withKeyMapper:self.__keyMapper importing:YES] : p.name;

The property is named importingToModel but at this stage we are exporting from the model. This is resulting in model properties like x_millis to be ouput as x_millis instead of xMIllis

**Comment by billinghamj** [comment]
#430 ;)

**Comment by billinghamj** [comment]
Discussed in detail in #491
