### ISSUE TITLE
EXC_BAD_ACCESS when using JSONModel multi threaded

### ISSUE THREAD

**Issue by hfossli** [icanzilb/JSONModel#441]
We have a multi threaded environment where multiple dictionaries is being parsed to JSONModel objects concurrently. I guess this is fairly common for the many users of JSONModel. 

First time JSONModel parses a dictionary for a class it is doing some setup and inspecting the class, caching the keymapper etc etc. 

Sometimes we get EXC_BAD_ACCESS in this method
```objective-c
-(BOOL)__customSetValue:(id<NSObject>)value forProperty:(JSONModelClassProperty*)property
{
    if (!property.customSetters)
        property.customSetters = [NSMutableDictionary new];

    NSString *className = NSStringFromClass([JSONValueTransformer classByResolvingClusterClasses:[value class]]);

    if (!property.customSetters[className]) {
        //check for a custom property setter method
        NSString* ucfirstName = [property.name stringByReplacingCharactersInRange:NSMakeRange(0,1)
                                                                       withString:[[property.name substringToIndex:1] uppercaseString]];
        NSString* selectorName = [NSString stringWithFormat:@"set%@With%@:", ucfirstName, className];

        SEL customPropertySetter = NSSelectorFromString(selectorName);
        
        //check if there's a custom selector like this
        if (![self respondsToSelector: customPropertySetter]) {
            property.customSetters[className] = [NSNull null];  <<<<<<<<<<<<<<<<<<<< EXC_BAD_ACCESS
            return NO;
        }
        
        //cache the custom setter selector
        property.customSetters[className] = selectorName;
    }
    
    if (property.customSetters[className] != [NSNull null]) {
        //call the custom setter
        //https://github.com/steipete
        SEL selector = NSSelectorFromString(property.customSetters[className]);
        ((void (*) (id, SEL, id))objc_msgSend)(self, selector, value);
        return YES;
    }
    
    return NO;
}
```
In case you are curious it didn't matter what the value of the variable `selectorName` was. Even values like `setAssetsWithNSDictionary:` and `setPrequintWithNSString:` had the same effect.

In order to reproduce the behavior we experienced in our live app we created a unit test where we parsed the same dictionary with the same class on 100 separate threads simultaneously. The crash happened consistently each time we ran the test. 

```objective-c
    NSOperationQueue *parserQueue = [[NSOperationQueue alloc] init];
    parserQueue.maxConcurrentOperationCount = 100;

    NSDictionary *parsedJSON = [NSJSONSerialization JSONObjectWithData:[json dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];

    for(int i = 0; i < 100; i++) {
        NSOperation *operation = [NSBlockOperation blockOperationWithBlock:^() {
            IVYArticleSummary *summary = [[IVYArticleSummary alloc] initWithDictionary:parsedJSON error:nil];
            NSLog(@"Parsed: %p", summary);
        }];
        [parserQueue addOperation:operation];
    }

    XCTestExpectation *expectation = [self expectationWithDescription:@"Wait for queue...."];

    [RACObserve(parserQueue, operationCount) subscribeNext:^(id x) {
        if([x intValue] == 0) {
            [expectation fulfill];
        }
    }];
    [self waitForExpectationsWithTimeout:100 handler:nil];
```

In order to mitigate this problem we did this in our base class (all classes inherits our base class which inherits JSONModel)

```objective-c

@interface IVYDataObject : JSONModel
@end

...

@interface IVYArticleSummary : IVYDataObject
@end

...

@implementation IVYDataObject

- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError **)err
{
    static NSMutableSet *classNames;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        classNames = [NSMutableSet new];
    });

    BOOL initSync;
    @synchronized([self class])
    {
        NSString *className = NSStringFromClass([self class]);
        initSync = ![classNames containsObject:className];
        if(initSync)
        {
            [classNames addObject:className];
            self = [super initWithDictionary:dict error:err];
        }
    }
    if(!initSync)
    {
        self = [super initWithDictionary:dict error:err];
    }
    return self;
}
```

This makes sure that the first to enter this synchronize block for a class (e.g. IVYArticleSummary) is being parsed it will happen synchronously. All other will just check synchronously if it can initialize without locking/being synchronized. 

Maybe a similar approach should be considered implemented in JSONModel to mitigate this problem for multi threaded environments. I think this problem was introduced with the release of 1.2.0, but I'm not certain of that.

**Comment by billinghamj** [comment]
Thanks - we're aware of this issue. Thanks for providing the synchronization code.

We're going to add synchronization around the process of finding the custom setters.

**Comment by billinghamj** [comment]
This is the same as #436, so I will close this one for now.

**Comment by hfossli** [comment]
Awesome!

**Comment by xilin** [comment]
Thanks for the fix. Hoping a new release that fix it.

**Comment by CIAlexanderAkimov** [comment]
@hfossli , your workaround works in our, but produces a little amount of crashes on 
"[classNames addObject:className];"
I noticed that "@synchronized([self class])" doesn't prevent different subclasses to mutate classNames subset in the same time.
So my suggestion is also to wrap all usages of "classNames" into "@synchronized(classNames)".

**Comment by hfossli** [comment]
I agree! That is the way to do it.

**Comment by yulichandra** [comment]
i already tried this solution, but still got same error?
