### ISSUE TITLE
Optional BOOL not working.

### ISSUE THREAD

**Issue by sudhiryadav** [icanzilb/JSONModel#444]
Hi, i am trying with the following and using the same model as given in your example but i still receive isInEurope : false
`+(BOOL)propertyIsOptional:(NSString*)propertyName
{
if ([propertyName isEqualToString: @"isInEurope"])
{
        return YES;
    }
    return NO;
}
`

In face i tried to return YES for all the properties but still doesn't work. 

Using JSON Model version 1.1.2. I am not using ver 1.2.0 because it doesn't work on xcode 6.4

**Comment by sudhiryadav** [comment]
Ok, i found out the issue. Actually i was trying to initialise the object like this:

`CountryModel *countryCheckNull = [CountryModel new];`

While it should have been : 
`CountryModel *countryCheckNull = [[CountryModel alloc] initWithString:@"" error:&err];`

Any explanations ?

**Comment by billinghamj** [comment]
The "Optional" flag relates primarily to deserialization, not serialization.

**Comment by sudhiryadav** [comment]
I am not able to understand I am creating an object 

`CountryModel *countryCheckNull = [CountryModel new];`

Then using optional params or propertyIsOptional i should be able to optionally skip the optional properties to be converted to Json. In fact it is working with other fields like NSString but not for primitive types.

Please do not close the thread. Its not resolved yet. If you want i can share a complete sample to you.

**Comment by billinghamj** [comment]
Yes, please provide:

- the full model (both interface and implementation)
- the full code you're using to operate on the model
- what you're expecting the result to be
- what the result currently is

**Comment by sudhiryadav** [comment]
Here is the complete reference attached, please note that JSONModel ver 1.1.2 and Xcode ver is 6.4.
Please note CountryModel.m
[JsonModelSample.zip](https://github.com/icanzilb/JSONModel/files/130470/JsonModelSample.zip)

Current Result: 
`Json Null Check String :  {"_id":0,"isInEurope":false,"dialCode":"234"}`

Expected Result:
`Json Null Check String :  {"_id":0,"dialCode":"234"}`

**Comment by billinghamj** [comment]
Right, so you don't want `isInEurope` to be outputted because you haven't set it (or have set it to `nil`)?

Ultimately, in Obj-C (or any C lang), there is absolutely no difference between `false` and `nil` - the value of both is actually zero. If you simply don't initialize `isInEurope`, or set it to `nil`, it will be equal to `false` (or `NO`).

To achieve the desired behavior, you have two options:

- change the type of `isInEurope` to `NSNumber *` which is an object type and can be `nil` (versus `BOOL` which is a value type and therefore cannot be `nil`)
- use `[country toJSONStringWithKeys:@[@"_id", @"dialCode"]]` rather than `[country toJSONString]`

This behavior is nothing to do with JSONModel - this is simply down to how C/Obj-C works.

**Comment by billinghamj** [comment]
See the definition of `nil`:

```c
#define nil __DARWIN_NULL
#define __DARWIN_NULL ((void *)0)
```

And `false`/`NO`:

```c
#define false 0
#define NO  ((BOOL)0)
```

**Comment by sudhiryadav** [comment]
So, do i assume that JSONModel does't support Primitive types Optional or Igonored features.

By the way many thanks for the support you gave till now.

**Comment by billinghamj** [comment]
JSONModel does support 'ignore' and 'optional' for primitive types.

The issue in this case is that the Objective-C runtime simply does not support the notion of a BOOL being `nil`. BOOL variables can be either true or false - nothing else. Similarly, other primitive types simply cannot be `nil`.

When serializing primitive types, the value can never be `nil` and therefore will always be included in the JSON output.
