### ISSUE TITLE
Mapping only declared properties

### ISSUE THREAD

**Issue by serhatsezer** [icanzilb/JSONModel#446]
I want to add custom property to my JSON mapping class but framework adds this property to mapping although i did not set this. Here is gist file.

https://gist.github.com/serhatsezer/1c0caf4d9a8657376dd5

**Comment by billinghamj** [comment]
Use `<Ignore>`, e.g.:

```objc
@property (nonatomic, copy) NSString <Ignore> *customProperty;
```
