### ISSUE TITLE
Map multiple keys to same object

### ISSUE THREAD

**Issue by imsrc21** [icanzilb/JSONModel#447]
I have two JSON.
**1 :** 

```json
{
  "status": 200,
  "data": {
    "id": "123",
    "title": "abc",
  }
}
```

**2 :** 

```json
{
  "status": 200,
  "data": {
    "id": "234",
    "name": "pqr",
  }
}
```

I want to map "title" and "name" keys to map same object in JSONModel.

```objc
@interface DataModel : JSONModel

@property (nonatomic,retain) NSString* id;
@property (nonatomic,retain) NSString* name; 
// i want to map name object with "title" and "name" keys in json

@end
```

Is this possible ?

**Comment by billinghamj** [comment]
Err, yeah I'd expect that to probably work. Have you tried using a KeyMapper? You should be able to map both `title` and `name` to `name.

The only thing to bear in mind is that when deserializing the object, you wouldn't get both `title` and `name` - only `name`.

**Comment by imsrc21** [comment]
@billinghamj How to map multiple keys to same object using KeyMapper ?

I tried this, but it did not work.
+(JSONKeyMapper*)keyMapper
{
    return [[JSONKeyMapper alloc] initWithDictionary:@{
                                                       @"title":@"name",
                                                       @"name":@"name"
                                                       }];
}

**Comment by billinghamj** [comment]
You'll probably need to use `initWithJSONToModelBlock:modelToJSONBlock:`

**Comment by hfossli** [comment]
This should probably work, but do note that the `-[JSONModel toDictionary]` method will choose one key (which is desired behavior after all) and you don't know up front which it will choose. Wrt to your example it may choose `title` or it may choose `name` as key for the `abc`/`pqr` value.

**Comment by hfossli** [comment]
Probably not important if you don't rely on the output of `-[JSONModel toDictionary]`. I don't.

**Comment by guojiubo** [comment]
Since `initWithJSONToModelBlock:modelToJSONBlock:` is Deprecated in version 1.3, is it still possible to map multiple keys to same property?

**Comment by billinghamj** [comment]
@guojiubo Please open a new issue to discuss that. Don't respond to this one - the existing people don't need the emails :)
