### ISSUE TITLE
NSDate or JSONValueTransformer not working for iOS 6.

### ISSUE THREAD

**Issue by neobie** [icanzilb/JSONModel#448]
I am using JSONValueTransformer to convert my API Date to NSDate.

```objc
@implementation JSONValueTransformer (Date)

NSString *APIDateFormat = @"yyyy-MM-dd HH:mm:ss";

- (NSDate *)NSDateFromNSString:(NSString*)string {
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:APIDateFormat];
    return [formatter dateFromString:string];
}

- (NSString *)JSONObjectFromNSDate:(NSDate *)date {
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    [formatter setDateFormat:APIDateFormat];
    return [formatter stringFromDate:date];
}

@end
```

It is working fine for iOS >= 8.0, but not working on iOS 6 on my iPod. in iOS 6, the date is null as print out by NSLog().
I can't test on iOS 7 yet as I do not have the device.

**Comment by billinghamj** [comment]
Seems to me that this is more likely to be an issue with your code than JSONModel.

Have you tried using other getters/setters with iOS 7?

**Comment by liruqi** [comment]
It's not working on my iOS 9.2.1. Method `- NSDateFromNSString: (NSString*)string` is not called.

**Comment by billinghamj** [comment]
This is the code which is supposed to make the setting happen: https://github.com/icanzilb/JSONModel/blob/dcb9c90bf4f1f2d7aee4dc4eeb73defec811d6c4/JSONModel/JSONModel/JSONModel.m#L1022

**Comment by billinghamj** [comment]
Sorry this actually: https://github.com/icanzilb/JSONModel/blob/dcb9c90bf4f1f2d7aee4dc4eeb73defec811d6c4/JSONModel/JSONModel/JSONModel.m#L444
