### ISSUE TITLE
JSONModel copy

### ISSUE THREAD

**Issue by pjebs** [icanzilb/JSONModel#449]
I have a subclass of JSONModel.

Let's call the subclass `MyModel`.

MyModel *a = ....

`[a copy]` performs only a shallow copy.
Is this intended behaviour?
How can I get it to do a deep copy so the NSDate * fields's values get copied over.

**Comment by pjebs** [comment]
Very strange. All other reference types get copied over EXCEPT NSDates.
My subclass implements a function that converts the incoming date string, parses it and converts it to NSDate. This part works perfectly because I NSLog the instance and see the NSDate. I can use the NSDate too. But `[a copy]` copies everything EXCEPT the NSDates.

-(void)setTimeStartWithNSString:(NSString *)time
{
    NSDateFormatter *dateFormat = [[NSDateFormatter alloc] init];
    [dateFormat setTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"GMT"]]; //Needed otherwise dateformatter assumes string is local time
    [dateFormat setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
    _timeStart = [dateFormat dateFromString:time];
}

**Comment by pjebs** [comment]
The NSDates are `nil` after the copy.

I'm assuming it must be a bug of some sort.

**Comment by pjebs** [comment]
In my subclass, I also reimplemented `copyWithZone` with exactly the same content as `copyWithZone` in the JSONModel base class (without calling super). That did not work either.

**Comment by billinghamj** [comment]
Hmm, we'll have a look at this.

I'd think that it should simply look for `copy` on the target object and try to use that, but it might not be doing so in some circumstances.

**Comment by billinghamj** [comment]
Okay so copying very simply serializes then deserializes the object - thus causing a copy to be made.

The serialization process uses `.toJSONString`.

Try running `.toJSONString` on the object you're trying to copy and inspect what value is outputted for the NSDate in question.

**Comment by billinghamj** [comment]
You're using a custom setter with a specific time format. You will probably need an equivalent getter (`JSONObjectForTimeStart`) which outputs that same format in order for the setter to work correctly. (As the setter will be called when deserializing after the copy.)

**Comment by pjebs** [comment]
The custom setter is only used to parse incoming data from an endpoint.
Once the incoming data (date string) has been parsed and a nsdate has been created, I no longer care about the date string when trying to copy my model.


Hence .tojsonstring shouldn't care about my date string. It doesn't even need to know that it was originally used to derive the nsdate.

I'm just trying to get the copy method to copy the nsdate field to the new instance.

**Comment by pjebs** [comment]
.tojsonstring should automatically deal with serialising a nsdate

**Comment by billinghamj** [comment]
@pjebs If you want help with this issue, you need to cooperate with me and stop being uppity. I am not paid to do this.

`toJSONString` does handle NSDate serialization out of the box. As I requested, please provide its output so I can diagnose the issue further.

As I explained above, I suspect the reason for the issue is your setter failing to deserialize dates formatted with the standard JSONModel NSDate format.

**Comment by pjebs** [comment]
NSLog of Model:

orig: <EventModel> 
   [maleAgeStart]: 0
   [preferences]: 0
   [tagline]: 
   [cityId]: 1
   [maleAgeEnd]: <nil>
   [femaleAgeStart]: 0
   [error]: <nil>
   [errorMessage]: <nil>
   [success]: 0
   [matches]: 0
   [id]: 8
   [femaleAgeEnd]: <nil>
   [registered]: 0
   [finished]: 0
   [timeEnd]: 2016-05-01 00:00:00 +0000
   [publicId]: 2
   [errorCode]: <nil>
   [maxMales]: 6
   [title]: Sample Event
   [maxFemales]: 5
   [timeStart]: 2016-05-01 00:00:00 +0000
   [watching]: 0
</EventModel>

**Comment by pjebs** [comment]
NSLog of Copy of Model

copy: <EventModel> 
   [id]: 8
   [timeEnd]: <nil>
   [timeStart]: <nil>
</EventModel>

**Comment by pjebs** [comment]
toJSONString:
`orig: {"id":"8","time_end":"2016-05-01T10:00:00+1000","time_start":"2016-05-01T10:00:00+1000"}`

**Comment by pjebs** [comment]
`copy:` 
`{"id":"8"}`

**Comment by pjebs** [comment]
Bear in mind my model implements:

+(BOOL)propertyIsOptional:(NSString*)propertyName
{
    return YES;
}

**Comment by pjebs** [comment]
It seems JSONModel is serializing the date ins RFC3339 format but that interferes with my customer setter which attempts to convert a date formatted in `yyyy-MM-dd HH:mm:ss` into a NSDate.

**Comment by billinghamj** [comment]
Yes exactly. As mentioned, JSONModel serializes then deserializes in order to copy.

JSONModel defaults to ISO8601 format but you're overriding that in the custom setter.

To resolve this, you also need to provide a custom getter. It might look something like this:

```objc
- (NSString *)JSONObjectForTimeStart
{
  NSDateFormatter *formatter = [NSDateFormatter new];
  formatter.timeZone = [NSTimeZone timeZoneWithAbbreviation:@"GMT"];
  formatter.dateFormat = @"yyyy-MM-dd HH:mm:ss";
  return [formatter stringFromDate:_timeStart];
}
```

**Comment by pjebs** [comment]
Thanks

**Comment by cbaggers** [comment]
Thanks @billinghamj the breakdown of this was much appreciated
