### ISSUE TITLE
Why avoid optional all properties?

### ISSUE THREAD

**Issue by serhatsezer** [icanzilb/JSONModel#453]
I'm using this feature and json model sent unnecessary properties.

```objc
@implementation ProductModel
+(BOOL)propertyIsOptional:(NSString*)propertyName
{
  return YES;
}
@end
```

here is shorted version my implementation code;

```objc
 @"ct" : @"Cities",
        @"tt" : @"Towns",
        @"wa" : @"WorkArea",
        @"kw" : @"Keyword",
```

and my interface file;

```objc
@property (nonatomic, copy) NSString *Cities;

//not in mobile
@property (nonatomic, copy) NSString *Towns;

@property (nonatomic, copy) NSString *WorkArea;

@property (nonatomic, strong) NSString *Keyword;
```

I just only set "Keyword" property and sent it to HTTP body. But its sent other properties with values like this;

```json
{"ct":"keyword", "tt":"some value", "wa":"", "kw":""}
```

My question is; setting all properties are optional may caused this result?

**Comment by billinghamj** [comment]
Provide all the code please - not just small snippets. If the code is long, you can put it in a [Gist](https://gist.github.com).

If JSONModel is serializing a value into an empty string, it is not nil and therefore will be outputted regardless of whether the property is marked as optional.

**Comment by serhatsezer** [comment]
@billinghamj , Here is interface file;
https://gist.github.com/serhatsezer/6672efa63bafcbe6f061

and implementation file;
https://gist.github.com/serhatsezer/919bbb039b4da482c901

I'm setting only keyword and city field like this;
 KNJobListParameter *jobListParameterModel = [[KNJobListParameter alloc] init];
  jobListParameterModel.Keyword = // getting from IB
  jobListParameterModel.Cities      = // getting from IB

and my json sent it to back-end side like this;

https://gist.github.com/serhatsezer/f5830a121cd848657e54

**Comment by billinghamj** [comment]
Something must be instantiating the other properties - there is no other way for them to end up as empty strings.

It would be helpful if you provided a **complete** example including the actual serialization call.

**Comment by serhatsezer** [comment]
OK. I will never use this framework again.

**Comment by billinghamj** [comment]
Oke 👍🏼

**Comment by serhatsezer** [comment]
@billinghamj I'm really sorry for this. It's my mistake!

**Comment by billinghamj** [comment]
So is the issue resolved? Or do you still need assistance?

You need to keep in mind that the maintainers of open source projects are generally not remunerated in any way. There's no obligation to provide support at all, so it's important to be gracious and polite.

**Comment by junestchick** [comment]
Hi, sorry for replying to this old topic, but setting all properties is ok?

**Comment by billinghamj** [comment]
If you want them to all be optional, sure.
