### ISSUE TITLE
[JSONModel toJSONString] not using keyMapper

### ISSUE THREAD

**Issue by pgawlowski** [icanzilb/JSONModel#454]
Let's assume I've got parent class
```
+(JSONKeyMapper*)keyMapper
{
    JSONKeyMapper *keyMapper = [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase];
    
    return [keyMapper initWithDictionary:@{
                                           @"id" : @"objectId"
                                           }];
}
```
Now I would like to have raw jsonString or even dictionary using keys from keyMapper.

Now matter what I try to do I've got correct underscore names for keys BUT 

> @"object_id" : (int)0	 

instead of 

> id

**Comment by billinghamj** [comment]
You should never initialize Objective-C classes twice. In this case, you are doing so.

This initializes the keymapper:

```objc
JSONKeyMapper *keyMapper = [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase];
```

Then this attempts to initialize it again. Doing this is not considered valid.

```objc
[keyMapper initWithDictionary:@{ @"id" : @"objectId" }];
```

What happens in this latter statement is that the instance will be entirely replaced and thus its behavior overridden. If I recall correctly, doing this can cause memory leaking or other similar issues.

There is currently no support for having layered/recursive key mapping. You could do this, however:

```objc
+ (JSONKeyMapper *)keyMapper
{
  JSONKeyMapper *baseKeyMapper = [JSONKeyMapper mapperFromUnderscoreCaseToCamelCase];

  return [JSONKeyMapper mapper:baseKeyMapper withExceptions:@{
    @"id" : @"object_id"
  }];
}
```

Note that the exceptions are not run after the existing "UnderscoreCaseToCamelCase" mapper. They bypass the base mapper entirely.
