### ISSUE TITLE
JSONModel refuses to parse strings in all caps with underscores.

### ISSUE THREAD

**Issue by fresh83** [icanzilb/JSONModel#460]
icanzilb .... Please answer valid Q's without closing them for no stated reason, these are big valid issues with your library your avoiding rather than solving. 

I have a API , that api sends users over a feed of statuses , these statuses all have a string type, here are the different types.

•STATUS
•PHOTO
•DEFAULT_PHOTO
•ALBUM
•VIDEO
•TOUCH_OFF

JSONModel works perfectly for all these content types BESIDES the ones with underscores. When converting the type property into a JSONModel something goes wrong that does not cause a error when converting the JSON array of dicts into a a array, but when my code actually needs to use one of these capitalized underscored values this happens: http://imgur.com/5GvQFDU   , to make matters weirder it seems like the var is not empty as you can see and if i try to log the type before this line of code is run it gives me hints in the error log that for some reason JSONModel is giving X-Code a var it thinks is a imgview (which I can assure you is not my doing, I dont play with the status objects after converting them to from json ) 

Ive inspected the JSON , nothing strange going on. It crashes on a object that in the original JSON has a type: DEFAULT_PHOTO   key/value  and the ultimate proof its a JSONModel issue....if on my API end I add a if(type==DEFAULT_PHOTO){    status.type=DEFAULT;   }  all my problems go away and there is no crash.

This leads me to believe strongly that JSONModel is doing something funky to manipulate my uppercase strings with underscores.  Hope this is detailed enough.

**Comment by icanzilb** [comment]
Dude you still fail to : 

1) ask nicely
2) provide a meaningful explanation of your problem

You just say there's nothing strange going on on your side which is NOT an explanation for me.

**Comment by fresh83** [comment]
Yeah ok have buggy code bc ur feelings are hurt & you are too lazy to fix anything.
