### ISSUE TITLE
How to ignore primitive types. Example float 、  double ......

### ISSUE THREAD

**Issue by FlyingNoob** [icanzilb/JSONModel#461]
When did I  define a enum for an object . But the json have not this key  . I want ignore this property .

**Comment by icanzilb** [comment]
Override this method http://cocoadocs.org/docsets/JSONModel/1.2.0/Classes/JSONModel.html#//api/name/propertyIsIgnored: in your model class. Return `YES` when the parameter is equal to a property name you want to ignore.
