### ISSUE TITLE
[Feature Request] More customizable kepMapper dictionary to convert json to model class

### ISSUE THREAD

**Issue by xingheng** [icanzilb/JSONModel#462]
AFAIK, JSONModel convert one JSON key structure to a specified model class, this is great for iOS client developer. Let's take this as an example,

Convert JSON string `{ "id": 1, "title": "foo"}` with keyMapper dictionary `@{@"id": @"ID", @"title": @"name"}`, I create a model class for students,

    @interface JMStudent : JSONModel
    @property (nonatomic, copy) NSString *ID;
    @property (nonatomic, copy) NSString *name;
    @end

The problem is, sometimes, the server returns some different JSON key `{ "studentid": 1, "studentName": "foo"}` for student info, there are several weird explains from backend developers. (sucks!)

I expected that passing a local dictionary variable as keyMapper to JSONModel and get right student class object (list) from different JSON string (NSDictionary).

Is that reasonable? If that, please confirm that whether the current latest version JSONModel could solved it? If not, I will fork & send a pull request about this.

Thanks!

**Comment by icanzilb** [comment]
Hey, you can create a __very__ flexible key mapper for your class. Have a look at: 
http://cocoadocs.org/docsets/JSONModel/1.2.0/Classes/JSONKeyMapper.html#//api/name/initWithJSONToModelBlock:modelToJSONBlock:

Using this method you can create a keymapper that just uses two blocks to convert keys and you can make it do whatever you want. In case the server is returning different keys for some reason - you can change your key mapper logic on the flight.

**Comment by billinghamj** [comment]
I think you could even subclass it if you really wanted :)

**Comment by xingheng** [comment]
Great thanks! That's what I looking for.

**Comment by Whirlwind** [comment]
`initWithJSONToModelBlock:modelToJSONBlock:` is deprecated, so not way to create a json to model mapper now.

**Comment by billinghamj** [comment]
Internally the library never actually used the JSONToModel block, so it has been removed. You can still do keymapping, but only in the modelToJSON direction

**Comment by Whirlwind** [comment]
@billinghamj we need the feature to support multi json format to a model. so there is not JSONToModel block to support it.

I think you should use the JSONToModel block rather than remove it.

**Comment by billinghamj** [comment]
Please open a new issue with a clear and well reasoned proposal. This issue is not simple.
