### ISSUE TITLE
an issue for  JSONModelArray

### ISSUE THREAD

**Issue by shaojiankui** [icanzilb/JSONModel#463]
i custom an NSArray category to avoid beyond bounds get array item

```objc
-(id)objectWithIndex:(NSUInteger)index{
    if (index <self.count) {
        return self[index];
    }else{
        return nil;
    }
}
```

and i use

```objc
@property(nonatomic,strong) NSArray<FolderModel,ConvertOnDemand> *appearances;
```

whe i use 

```objc
FolderModel *folder =  [appearances objectWithIndex:index];
```

the 'folder' become an NSDictionary instance,not a FolderModel model instance

it will crash

**Comment by billinghamj** [comment]
Could you show the JSON you're deserializing?

**Comment by shaojiankui** [comment]
[JSONModelArray-Demo.zip](https://github.com/icanzilb/JSONModel/files/191798/JSONModelArray-Demo.zip)

run the JSONModelArray-Demo.zip will show this bug

**Comment by billinghamj** [comment]
You're making a category on NSArray, but JSONModelArray isn't an NSArray - it doesn't subclass NSArray.

If you need to rely on the exact behavior of an actual NSArray, don't use `ConvertOnDemand`.

**Comment by billinghamj** [comment]
That being said, I think we probably should just subclass NSArray...

@icanzilb Any reason we don't subclass NSArray? We're currently just making an NSArray-like class, but  not subclassing it.

**Comment by billinghamj** [comment]
@shaojiankui Could you try this again against my PR #464?

**Comment by billinghamj** [comment]
@shaojiankui Okay, we've officially removed support for `ConvertOnDemand` as it no longer serves a practical purpose. Simply remove the protocol from your property and everything will work as expected.

**Comment by shaojiankui** [comment]
it works! @billinghamj  thanks!
