### ISSUE TITLE
Detect Array in json object

### ISSUE THREAD

**Issue by gauuni** [icanzilb/JSONModel#465]
I have an json object with a property that is an array, but sometime this property is return an array with just only one object inside and your lib cannot detect it.
So how I can resolve this problem

Example:
json : [{
{data: "abc"},
{data: "xyz"}]
Sometime it's return like this:
json : [{
{data: "xyz"}]
And I received this error message
UserInfo={kJSONModelTypeMismatch=Property 'Image' is declared as NSArray<LayoutImage>* but the corresponding JSON value is not a JSON Array., NSLocalizedDescription=Invalid JSON data. The JSON type mismatches the expected type. Check the error user information., kJSONModelKeyPath=Page[2].Image}

**Comment by billinghamj** [comment]
JSONModel should not have any problems with handling arrays containing only one value.

Could you attach sample JSON input, your model code, and the code you're running to deserialize?

**Comment by gauuni** [comment]
Actually this is XML response, I use this function to convert to dictionary 
`+(NSDictionary *)dictionaryFromResponse:(id)response{
    NSString *responseString = response;
    XMLDictionaryParser *parser = [XMLDictionaryParser sharedInstance];
    parser.attributesMode = XMLDictionaryAttributesModeUnprefixed;
    NSDictionary *dict = [parser dictionaryWithString:responseString];
    return dict;
}`
And this is the result:
`Image =     (
                {
            Angle = 0;
            LayoutRect = "0,0,1800,1200";
        },
                {
            Angle = 0;
            LayoutRect = "1800,0,3600,1200";
        }
    );
},
{
    Image =     (
                {
            Angle = 0;
            LayoutRect = "175,120,1625,1080";
        },
                {
            Angle = 0;
            LayoutRect = "1975,120,3425,1080";
        }
    );
},
{
    Image =     {
        Angle = 0;
        LayoutRect = "0,0,3600,1200";
    };
},
)`

As you see the last is have just one object

`@protocol LayoutInfo
@end
@protocol LayoutPage
@end
@protocol LayoutImage
@end

@interface LayoutObject : JSONModel
@property (nonatomic, strong) NSString *_name;
@property (nonatomic, strong) NSArray<LayoutInfo> *info;
@end

@interface LayoutInfo : JSONModel
@property (nonatomic, strong) NSString *booktype;
//@property (nonatomic, assign) BookDirection direction;
@property (nonatomic, strong) NSArray<LayoutPage> *Page;
@end

@interface LayoutPage : JSONModel
@property (nonatomic, strong) NSArray<LayoutImage> *Image;
@end

@interface LayoutImage : JSONModel
@property (nonatomic, strong) NSString *Angle;
@property (nonatomic, strong) NSString *LayoutRect;
@property (nonatomic, assign) CGFloat left;
@property (nonatomic, assign) CGFloat top;
@property (nonatomic, assign) CGFloat right;
@property (nonatomic, assign) CGFloat bottom;
@end`
Above is code is file .h

You can refer full data in this link http://www.vivipri.co.jp/photobookMac/xml/Layout_new.xml

**Comment by billinghamj** [comment]
Okay, so the equivalent JSON for the object you have above looks like this:

```json
[
  {
    "Image": [
      {
        "Angle": 0,
        "LayoutRect": "0,0,1800,1200"
      },
      {
        "Angle": 0,
        "LayoutRect": "1800,0,3600,1200"
      }
    ]
  },
  {
    "Image": [
      {
        "Angle": 0,
        "LayoutRect": "175,120,1625,1080"
      },
      {
        "Angle": 0,
        "LayoutRect": "1975,120,3425,1080"
      }
    ]
  },
  {
    "Image": {
      "Angle": 0,
      "LayoutRect": "0,0,3600,1200"
    }
  }
]
```

The problem is that the last `Image` object is not an array containing one object. It just isn't an array at all. JSONModel doesn't handle turning this into an NSArray because it isn't a JSON array.

**Comment by billinghamj** [comment]
The options I think you have are:

- change the configuration of your XML parser to always output a consistent NSDictionary structure (as in, always output arrays, even if there is only one of a particular object)
- create a custom setter to handle this case

It's important to recognize that JSONModel is designed to work with JSON - where typing inconsistencies are not possible. It is not intended for use with formats like XML and does not support them. As such, we will not be changing JSONModel's behavior in this case, but I think you should have the necessary tools available to override its behavior yourself.

**Comment by gauuni** [comment]
Thanks for your support. I have found how to fix this problem.

**Comment by gauuni** [comment]
It still has occurred a problem. It recognised as an Array but still give error : 
Printing description of err:
(NSError **) err = 0x00007fff5fbfd838 domain: class name = __NSArrayM - code: 106102874453120
What does it mean?

**Comment by billinghamj** [comment]
That error code looks like uninitialized memory, so it doesn't really mean anything. Does it consistently output exactly the same thing?

**Comment by gauuni** [comment]
I have resolved that problem. It's quite weird, if I use exactly that classname "LayoutInfo" the object always contain 0 objects. Then I change to another name, it worked. I don't know why is that.
