### ISSUE TITLE
Unable to handle integer/string array responses using JSONModel

### ISSUE THREAD

**Issue by SiddarthaPolisetty** [icanzilb/JSONModel#467]
{
	"suite_id": 1,
	"name": "This is a new test run",
	"assignedto_id": 5,
	"include_all": false,
	"case_ids": [1, 2, 3, 4, 7, 8]
}

What approach should i use to map "case_ids" which is an array of integers

**Comment by SiddarthaPolisetty** [comment]
Sorry, False Alarm.

**Comment by wayone** [comment]
How do you deal with it ?

**Comment by billinghamj** [comment]
It should default to an NSNumber without explicit configuration, as that is the only valid number type within an NSArray (cannot contain primitive types).
