### ISSUE TITLE
Crash on compare methods

### ISSUE THREAD

**Issue by YoavJivi** [icanzilb/JSONModel#470]
I've been getting crashes from the compare method saying:

"Can't compare models with no \<Index\> property", i couldn't find any documentation as to why is that happening.

Help would be appreciated.

Yoav

**Comment by billinghamj** [comment]
https://github.com/icanzilb/JSONModel/blob/03a90f47cb4f79bf8dda05a2c2cc40089179bd18/JSONModel/JSONModel/JSONModel.h#L53-L61

**Comment by billinghamj** [comment]
You need to define what property uniquely identifies the instance of the model.

JSONModel uses that to differentiate them.

**Comment by YoavJivi** [comment]
Hi thanks for the answer
I've ben using JSONModel pod for two apps now and i never had to create a property to uniquely identify my object. Why is it crashing now?

**Comment by billinghamj** [comment]
Because you're using a feature which requires this ability.

You could flag a property as the `Index`, then return some kind of generated hash from it.

**Comment by billinghamj** [comment]
If you think this is a bug, you'll need to provide:

- the full input - JSON, NSDictionary, or whatever
- complete model header & implementation files
- the code you're running which causes the exception
