### ISSUE TITLE
Mapping array of objects to one object

### ISSUE THREAD

**Issue by pgawlowski** [icanzilb/JSONModel#472]
Hello,
API I'am forced to use got a little bit rusty data model (and I'm not able to change it). So we've got something like below.
```
{
  groups=({
    key="VALUE_1";parameters={
      
    };version=0;
  },
  {
    key="VALUE_2"parameters={
      
    };version=0;
  },
  {
    key="VALUE_3";parameters={
      
    };version=0;
  });
version=0;
}
```
Yes - there is LITERALLY key.

What I was trying to do is to ignore fact that groups is an NSArray and treat it like 3 objects of same class.
So I've got objects like
**MainObject**
`@property (nonatomic, retain) GroupObject *groups;`

**GroupObject**
```
@property (nonatomic, retain) Group *value_1;
@property (nonatomic, retain) Group *value_2;
@property (nonatomic, retain) Group *value_3;
```

My **GroupObject** got
```
- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError *__autoreleasing *)err {
    if ((self = [super init])) {
        for (NSDictionary *element in dict) {
            if ([[element valueForKey:@"key"] isEqualToString:@"VALUE_1"]) {
                self.value_1 = [[Group alloc] initWithDictionary:element error:nil];
            } else if ([[element valueForKey:@"key"] isEqualToString:@"VALUE_2"]) {
                self.value_2 = [[Group alloc] initWithDictionary:element  error:nil];
            } else if ([[element valueForKey:@"key"] isEqualToString:@"VALUE_3"]) {
                self.value_3 = [[Group alloc] initWithDictionary:element error:nil];
            }
        }
    }
    
    return self;
}
```

The GroupObject in return self; is initialized correctly. Then we're moving to JSONModel.m to ___importDictionary_ method and in line 387 
```
                if (![value isEqual:[self valueForKey:property.name]]) {
                    [self setValue:value forKey: property.name];
                }
```
after _If_ I've got 
`self	MainObject *	@"0 objects"	0x79fde270`
value is correct object of GroupObject, property.name is equal to "groups" and it's not setting the value for property.name. 

Where is the problem?

**Comment by billinghamj** [comment]
Please provide the original JSON. What you have shown above is not JSON.

JSONModel can parse arrays fine. It will be up to you to map from the array to an object with 3 items.

**Comment by pgawlowski** [comment]
I am not able to provide original JSON (cause of NDA ;) ) but this is the original scheme with changed data/names.
x, y and VALUE_ is just mock data, rest are the original keys.

```
{
  "groups": [
    {
      "parameters": {
        "x": "y",
      },
      "key": "VALUE_1",
      "version": 0
    },
    {
      "parameters": {
        "x": "y",
      },
      "key": "VALUE_2",
      "version": 0
    },
    {
      "parameters": {
        "x": "y",
      },
      "key": "VALUE_3",
      "version": 0
    }
  ],
  "version": 0
} 
```

**Comment by pgawlowski** [comment]
Ok I found the problem. It was well known Xcode Derived Data issue - it was not making correct instance of object because of wrong compilation. Not JSONModel isseue. Sorry for taking your time. Thank you for your help.

**Comment by billinghamj** [comment]
No problem. 😄  Let us know if you need anything else.
