### ISSUE TITLE
NSArray type not supported

### ISSUE THREAD

**Issue by rjmiller2543** [icanzilb/JSONModel#476]
I'm using this for an iOS application and I'm having an exception thrown for:
*** Terminating app due to uncaught exception 'Type not allowed', reason: 'NSArray type not supported for ClubModel.memberships'

However, it's explicitly declared as an NSArray in the model:
`@property(strong,nonatomic) NSArray<ClubMembershipsModel*><ConvertOnDemand> *memberships;
`
and the ClubMembershipsModel is also declared as a JSONModel:
`@interface ClubMembershipsModel : JSONModel

@property(copy,nonatomic) NSString *joined_at;
@property(copy,nonatomic) NSString *level;
@property(copy,nonatomic) NSString *member_id;
@property(copy,nonatomic) NSString *name;
@property(copy,nonatomic) NSString *picture_location;
@property(copy,nonatomic) NSString *added_by_id;
@property(copy,nonatomic) NSString *added_by_name;`

Because of security issues with Firebase, we have to initialize it in a slightly funny way:

           `NSMutableArray<NSDictionary*> *temparray = [[NSMutableArray alloc] init];
             for (id key in snapshot.value) {
                 NSMutableDictionary *newdictmodel = [snapshot.value valueForKey:key];
                 
                 [temparray addObject:newdictmodel];
             }
             NSArray<ClubMembershipsModel*> *clubMemberships = [ClubMembershipsModel arrayOfModelsFromDictionaries:temparray error:&error];
              dict = [NSDictionary dictionaryWithObject:clubMemberships forKey:kClubMembershipsKey];`

Any guidance is much appreciated..

Thanks,
RM

**Comment by suqiang** [comment]
ask the same question.. Any guidance is much appreciated..

**Comment by billinghamj** [comment]
@suqiang - do not continue this issue. Create a new one please, providing your model code and JSON.

**Comment by suqiang** [comment]
thanks for reply. i have solve the problem. our server is not stable, some it give NSArray when I need  custom object...
