### ISSUE TITLE
Unkown Object Keys.

### ISSUE THREAD

**Issue by regiside** [icanzilb/JSONModel#477]
My JSON has some keys that are auto incremented so I don't know what they will be when retreving them. Is there a way to use JOSNModel to create a model that accounts for this? (See example below.)

![screen shot 2016-05-01 at 8 42 14 pm](https://cloud.githubusercontent.com/assets/10213359/14946798/4ae024cc-0fdd-11e6-97be-fe7948f0e0a4.png)

Thanks so much for this amazing library!

**Comment by billinghamj** [comment]
Yep!

```objc
@protocol Item;

@interface MyModel : JSONModel
@property (strong, nonatomic) NSDictionary <Item> *items;
@end

@interface Item : JSONModel
@property (strong, nonatomic) NSString *id;
@property (strong, nonatomic) NSString *unique_id;
@property (strong, nonatomic) NSString *name;
@end
```

**Comment by billinghamj** [comment]
If you want to use Obj-C's built in generics support as well, you can do this:

```objc
@protocol Item;

@interface MyModel : JSONModel
@property (strong, nonatomic) NSDictionary <NSString *, Item *> <Item> *items;
@end
```

Using just the Obj-C generics syntax without the JSONModel protocol will not work.

**Comment by regiside** [comment]
Thanks so much! This worked perfectly!
