### ISSUE TITLE
Module map issue in JSONModel framework built with Carthage

### ISSUE THREAD

**Issue by ccbb** [icanzilb/JSONModel#481]
Hi,

I am trying to include JSONModel into a project using Carthage and having an issue with the built framework.

It is a problem that the auto generated module map in the framework does not contain JSONModelLib.h but rather JSONModel.h. I believe Xcode uses the umbrella header with the same name of the framework in the module map file and therefore includes JSONModel.h in the file.

Is this something that others have come across or am I missing something?

Otherwise it can be fixed with a custom module map with the following contents:

framework module JSONModel {
  umbrella header "JSONModelLib.h"

  export *
  module * { export * }
}

This is then referenced in the build settings. I can make a pull request with the change.

-Cail

**Comment by billinghamj** [comment]
Yes, please PR if that would be the correct way to handle it.

@cybertk: I'd appreciate it if you could take a look at this also.
