### ISSUE TITLE
Assign JSONArray of Strings using JSONModel

### ISSUE THREAD

**Issue by LilJeff2626** [icanzilb/JSONModel#483]
I am trying to use JSON Model to parse the following:

```json
"loans": [
{
  "id": 98765,
  "name": "Jeffrey",
  "description": {
    "languages": ["es","en"]
  },
  "status": "fundraising",
  "funded_amount": 26,
 "location":{"country_code":"BO","country":"Bolivia","town":"Santa Cruz"}
```

KivaFeed.h

```objc
@interface KivaFeed : JSONModel
@property (strong, nonatomic) NSArray<LoanModel, ConvertOnDemand>* loans;
@end
```

LoanModel.h

```objc
@protocol LoanModel @end
@interface LoanModel : JSONModel
@property (strong, nonatomic) NSString* name;
@property (strong, nonatomic) NSString* status;
@property (strong, nonatomic) NSString* use;
@property (strong, nonatomic) Description* description;
@property (strong, nonatomic) LocationModel* location;
```

Description.h

```objc
@interface Description : JSONModel
@property (strong, nonatomic) NSArray<Languages*>*languages; 
@end
```

Languages.h

```objc
@protocol Languages
@end
@interface Languages : JSONModel
@end
```

From previous readings / analysis it appears i need to establish a protocol using NSString
in the Languages.h class?

When I run the following code, I get:

```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<LoanModel 0x7fd0d8534be0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key description.'
```

I must have Languages.h coded incorrectly....

How do you use JSONModel, to properly parse the following:

```
"languages": ["es","en"]
```

Where do I establish NSString as the only valid data type for that class.

Only been working in iOS for 6 months.....

Thanks for your help!

**Comment by billinghamj** [comment]
Okay so the JSON you've provided isn't quite valid, but I will assume it is actually this:

```json
{
	"loans": [
		{
			"id": 98765,
			"name": "Jeffrey",
			"status": "fundraising",
			"funded_amount": 26,
			"description": {
				"languages": ["es", "en"]
			},
			"location": {
				"country": "Bolivia",
				"country_code": "BO",
				"town": "Santa Cruz"
			}
		}
	]
}
```

Your model classes could look like this:

```objc
@protocol Loan;

@interface MyModel : JSONModel
@property (strong, nonatomic) NSArray <Loan *> <Loan> *loans;
@end

@interface Loan : JSONModel
@property (strong, nonatomic) NSInteger *id;
@property (strong, nonatomic) NSString *name;
@property (strong, nonatomic) NSString *status;
@property (strong, nonatomic) NSInteger *funded_amount;
@property (strong, nonatomic) Description *description;
@property (strong, nonatomic) Location *location;
@end

@interface Description : JSONModel
@property (strong, nonatomic) NSArray <NSString *> *languages;
@end

@interface Location : JSONModel
@property (strong, nonatomic) NSString *country;
@property (strong, nonatomic) NSString *country_code;
@property (strong, nonatomic) NSString *town;
@end
```

It's worth noting that `ConvertOnDemand` has been removed/deprecated. It's also worth nothing that this JSON would not deserialize because `use` is missing, which would fail validation. Just add `<Optional>` if it is not required.

**Comment by LilJeff2626** [comment]
I coded it exactly how you have it.
Its still failing on the assignment of the description.

IF I have Loan coded like below it works:

@interface Loan : JSONModel
@property (assign, nonatomic) int id;
@property (strong, nonatomic) NSString *name;
@property (strong, nonatomic) NSString *status;
@property (strong, nonatomic) NSString *use;
@property (assign, nonatomic) int funded_amount;
//@property (strong, nonatomic) Description *description;
@property (strong, nonatomic) Location *location;

When I uncomment the Description line, its failing.

@interface Loan : JSONModel
@property (assign, nonatomic) int id;
@property (strong, nonatomic) NSString *name;
@property (strong, nonatomic) NSString *status;
@property (strong, nonatomic) NSString *use;
@property (assign, nonatomic) int funded_amount;
@property (strong, nonatomic) Description *description;
@property (strong, nonatomic) Location *location;

@interface Description : JSONModel
@property (strong, nonatomic) NSArray <NSString *> *languages;
@end

2016-05-12 10:06:54.325 JSON_HelloWorld[18304:62926] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Loan 0x7fa9a1d52180> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key description.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c86dc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c506bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010c86d8a9 -[NSException raise] + 9
	3   Foundation                          0x000000010be5ab53 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 259
	4   JSON_HelloWorld                     0x000000010aa79399 -[JSONModel initWithDictionary:error:] + 3881
	5   JSON_HelloWorld                     0x000000010aa7c7ef +[JSONModel arrayOfModelsFromDictionaries:] + 527
	6   JSON_HelloWorld                     0x000000010aa7aff1 -[JSONModel __transform:forProperty:] + 945
	7   JSON_HelloWorld                     0x000000010aa7942d -[JSONModel initWithDictionary:error:] + 4029
	8   JSON_HelloWorld                     0x000000010aa83cb2 __58-[JSONModel(Networking) initFromURLWithString:completion:]_block_invoke + 146

It seems like this is an error some other developers are running into using the JSONModel.

Trying to code for a generic string list on a key

           "description": {
                "languages": ["es", "en"]
            },

**Comment by HerrDoktorBD** [comment]
Try putting
    @synthesize description = _description;
inside your implementation (*.m).

**Comment by billinghamj** [comment]
Ah yes, you will need to do the above, though I think you can just do:

```objc
@synthesize description;
```

This is because 'description' is a special property in Obj-C. You may wish to change the property name and use a JSONKeyMapper to convert the name.

**Comment by LilJeff2626** [comment]
Thanks HerrDoktorBD / billinghamj.  That worked!
