### ISSUE TITLE
Additional keys in the JSON string should not cause the mapping to fail

### ISSUE THREAD

**Issue by adil-hussain-84** [icanzilb/JSONModel#484]
If there's a key in the JSON string for which there's no field in my data object, I would like the parsing to still succeed. Is this possible? I believe not.

For example, if I have a data model that contains a single field as follows...

    @property(nonatomic, strong) NSString *keyA;

... and the JSON string is as follows...

    "{\"keyA\":\"valueA\",\"keyB\",\"valueB"}"

... then it would be great if the mapping of `keyA` succeeded and the extra key in the JSON was ignored.

(This is useful in case the server response that my app receives is added to, older versions of my app that are not expecting this key should not fail.)

**Comment by billinghamj** [comment]
Yes this should be fine. This would not error.

The JSON string you have there is invalid though. You have a comma between "keyB" and "valueB" which should actually be a colon.

**Comment by adil-hussain-84** [comment]
@billinghamj Yup... That'll do it. D'oh! Thanks for your help.
