### ISSUE TITLE
Optional and type specification not respected for NSArray

### ISSUE THREAD

**Issue by adil-hussain-84** [icanzilb/JSONModel#485]
I'm using version 1.2.0 of the library (the latest at the time of writing this issue). I have an object specified as follows:

    #import <Foundation/Foundation.h>
    #import "InnerObject.h"
    #import "JSONModel.h"

    @interface OuterObject : JSONModel

    @property(nonatomic, assign) NSNumber<Optional> *resultCount;
    @property(nonatomic, strong) NSArray<Optional, InnerObject*> *results;

    @end

i.e. I want `results` to be optional and when it is specified I want the items to be of type `InnerObject`.

However, I'm finding that both the `Optional` and `InnerObject` specifications are being ignored.

I can only parse a JSON object to an instance of `OuterObject` if the JSON object has a `results` key. And I'm finding that the items in `OuterObject.results` remain as `NSDictionary` objects and are not themselves mapped to `InnerObject`.

Any idea what I am doing wrong?

**Comment by billinghamj** [comment]
Your property declaration is invalid. It needs to look like either of these two options:

```objc
@protocol InnerObject;

@property (nonatomic, strong) NSArray <InnerObject *> <Optional, InnerObject> *results;
@property (nonatomic, strong) NSArray <Optional, InnerObject> *results;
```

**Comment by adil-hussain-84** [comment]
@billinghamj I tried different variants of `InnerObject` and `Optional` on `results`. Looks like the `@protocol` declaration of `InnerObject` is what I was missing! Many thanks for your help. It's working now.

**Comment by adil-hussain-84** [comment]
@billinghamj Great library btw. So much easier and intuitive to use than others that I'm comparing it against. So little plumbing code required to get it to work.
