### ISSUE TITLE
toDictionary using original keys not mapped ones

### ISSUE THREAD

**Issue by gmogames** [icanzilb/JSONModel#486]
Hello there,

In my model I have the following properties:

```objc
@property (nonatomic, strong) NSString<Optional>*message_id;
@property (nonatomic, strong) NSString *title;
@property (nonatomic, assign) int read;
```

but the "read" property is actually keymapped from "status"

```objc
+(JSONKeyMapper*)keyMapper
{
    return [[JSONKeyMapper alloc] initWithDictionary:@{@"status": @"read"}];
}
```

All good so far, but I'm able to call my API again sending these parameters to mark this message as read, so in the code I change the model to use `message.read = 1`, but when I send my model to the API using `[obj toDictionary]`, the key used to put this dictionary together is `read` and not `status`, the original key used by the API.

I could just before sending the dictionary to the api, create one from scratch, but it would be nice if there were a way to get the dictionary version of my JSONModel model that would return the original keys, not the ones used in the model.

Thanks!

**Comment by billinghamj** [comment]
Hmm that does sound like a bug. Could you also provide the code you're using to (de)serialize?

**Comment by billinghamj** [comment]
Ah actually this looks like it is probably the same issue as #430 and #438.

If you'd be willing to add the necessary tests to #430, I can get this resolved.
