### ISSUE TITLE
JSONModel object prints nil as value in lldb, but the value is actually there?

### ISSUE THREAD

**Issue by dhiraj** [icanzilb/JSONModel#487]
I'm going a bit crazy trying to debug why this is happening. I've got an NSMutableArray from the ```arrayOfModelsFromDictionaries``` method, and when I debug it looks to not be working, because all values are nil. But when I go deeper and try to check the actual property, it prints! Any ideas / suggestions why this could be happening?

Have a look at the lldb console output below, Entity is my JSONObject model class.
```
(lldb) po self.services[0]
<Entity> 
   [ModifiedBy]: <nil>
   [EntityProperties]: <nil>
   [EntitySchemaVersion]: <nil>
   [ReferenceID]: <nil>
   [ID]: <nil>
   [EntitySchema_ID]: <nil>
   [ModifiedOn]: <nil>
   [CreatedOn]: <nil>
   [IsDeleted]: <nil>
   [CreatedBy]: <nil>
</Entity>

(lldb) po [self.services[0] ModifiedBy]
admin
```

**Comment by billinghamj** [comment]
I haven't seen anything along these lines. For something like this, we'll need you to make an Xcode project which consistently reproduces the issue when run. Then we'll be able to figure it out. Thanks.

**Comment by dhiraj** [comment]
Ok, I'll try to fix up a project which is doing this. I have a feeling it could be some sort of threading issue, maybe?

I'm currently working on it just accessing values while checking if they're valid, will try to get a sample project submitted when possible.

**Comment by billinghamj** [comment]
It sounds more like a bug in Xcode's debugger to me, but yeah maybe.

**Comment by dhiraj** [comment]
Figured out the problem, closing the issue.

I'd inadvertently overridden the ```valueForKey:``` method in my model, and was not returning the right things. All apologies for wasting your time.

**Comment by billinghamj** [comment]
No worries :)
