### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by expkzb** [icanzilb/JSONModel#488]
![2016-05-27 3 41 20](https://cloud.githubusercontent.com/assets/1467947/15601412/ba49d684-2421-11e6-8bc9-ce006e7b63ab.png)
![2016-05-27 3 41 30](https://cloud.githubusercontent.com/assets/1467947/15601421/c93da602-2421-11e6-94ef-e15d57574542.png)
Add properties from B to A automatically at run time then do the rest mapping things
![2016-05-27 3 41 49](https://cloud.githubusercontent.com/assets/1467947/15601423/cdd20d20-2421-11e6-9596-f21d5e847e48.png)

**Comment by billinghamj** [comment]
You can do this with inheritance.

```objc
@interface A : B
```

JSONModel does not aim to support mapping of data into a different structure from the original JSON. It only aims to map directly from the JSON to the exact equivalent Obj-C classes with full validation.

**Comment by expkzb** [comment]
@billinghamj Well, I learned that the feature is called "mixin". It should be implemented by the program language.
