### ISSUE TITLE
JSONKeyMapper is only ever used one-way

### ISSUE THREAD

**Issue by billinghamj** [icanzilb/JSONModel#491]
I have been trying to diagnose some issues with key mapping and have come to the realization that keys are only mapped Model->JSON. There is no circumstance whatsoever where a key mapper will be used JSON->Model.

To demonstrate this, I have removed the ability entirely to have JSON->Model mappings, and all tests pass as normal. See: https://github.com/icanzilb/JSONModel/tree/james/keymapper-issue

The question now is what we should do about it. I see two possible options:

- strip out all JSON->Model mapping and flag all methods accepting this mapping as deprecated
- add actual support for JSON->Model mapping

The first option would definitely be non-breaking. The second option could be breaking, but only if the API was used incorrectly to start with.

I am inclined to think that we should go with the first option for now, maintaining the behavior but making it clear in the API. Then later down the line, perhaps for a JSONModel v2 release, we could add real support for two-way mapping.

Any thoughts @icanzilb / others?

**Comment by billinghamj** [comment]
@icanzilb / others - Unless you say otherwise, I'll go ahead and implement the first option by merging #492. Let me know if you have any concerns and we can discuss :)

**Comment by icanzilb** [comment]
In `KeyMappingTests.m` under `testExceptionsMapper` I can see the following test code:

```
NSString *jsonString = @"{\"ID\":\"12345\",\"NAME\":\"TEST\"}";
RenamedPropertyModel *m = [[RenamedPropertyModel alloc] initWithString:jsonString error:nil];
XCTAssertNotNil(m, @"Could not initialize model from string");
```

Isn't this JSON->Model mapping, which you say it's missing? Or am I understanding the issue wrong?

**Comment by icanzilb** [comment]
Sorry the test code goes on to check for the mapped property:
```
 XCTAssertEqualObjects(m.identifier, @"12345", @"identifier does not equal '12345'");
XCTAssertEqualObjects(m.name, @"TEST", @"name does not equal 'TEST'");
```

**Comment by billinghamj** [comment]
So the mapping does work in both directions, but it is only ever done by mapping from the model property keys to the JSON property keys.

In the "import dictionary" method, the model's properties are enumerated and mapped to the JSON property keys. The resulting mapped key is then used to do e.g.: `[instance setValue[dict getValueForKeyPath:mappedKey forKeyPath:property.key]`.

In the "to dictionary" method, the model's properties also are enumerated and mapped to the JSON property keys. The mapped key is used to do e.g.: `dict[mappedKey] = [instance getValueForKeyPath:property.key];`

So the model property keys are always enumerated and then mapped to the JSON keys. There is never any circumstance where the JSON dictionary is enumerated and mapped to the model property keys.

**Comment by billinghamj** [comment]
Put a bit more simply, it just means that `JSONToModelKeyBlock` is never used and `modelToJSONKeyBlock` is always used.

**Comment by icanzilb** [comment]
Now I see. Maintaining compatibility sounds priority to me

**Comment by billinghamj** [comment]
Okay so the contents of PR #492 maintains precisely the same behavior and no APIs have been removed, but flags all parts of the API which show JSON->Model as deprecated. An equivalent API has been added which is just one-way.

**Comment by billinghamj** [comment]
Great. Now could just do with cutting a release really. Could you do that when you get a chance please @icanzilb?

**Comment by icanzilb** [comment]
Sure thing @billinghamj: today or tomorrow
